// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// HelpMode provides a mock function for the type MockConfig
func (_mock *MockConfig) HelpMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HelpMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_HelpMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HelpMode'
type MockConfig_HelpMode_Call struct {
	*mock.Call
}

// HelpMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) HelpMode() *MockConfig_HelpMode_Call {
	return &MockConfig_HelpMode_Call{Call: _e.mock.On("HelpMode")}
}

func (_c *MockConfig_HelpMode_Call) Run(run func()) *MockConfig_HelpMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_HelpMode_Call) Return(b bool) *MockConfig_HelpMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_HelpMode_Call) RunAndReturn(run func() bool) *MockConfig_HelpMode_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockConfig
func (_mock *MockConfig) Version() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfig_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockConfig_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockConfig_Expecter) Version() *MockConfig_Version_Call {
	return &MockConfig_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockConfig_Version_Call) Run(run func()) *MockConfig_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_Version_Call) Return(s string) *MockConfig_Version_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfig_Version_Call) RunAndReturn(run func() string) *MockConfig_Version_Call {
	_c.Call.Return(run)
	return _c
}

// VersionMode provides a mock function for the type MockConfig
func (_mock *MockConfig) VersionMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for VersionMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_VersionMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VersionMode'
type MockConfig_VersionMode_Call struct {
	*mock.Call
}

// VersionMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) VersionMode() *MockConfig_VersionMode_Call {
	return &MockConfig_VersionMode_Call{Call: _e.mock.On("VersionMode")}
}

func (_c *MockConfig_VersionMode_Call) Run(run func()) *MockConfig_VersionMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_VersionMode_Call) Return(b bool) *MockConfig_VersionMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_VersionMode_Call) RunAndReturn(run func() bool) *MockConfig_VersionMode_Call {
	_c.Call.Return(run)
	return _c
}

// WatchdogMode provides a mock function for the type MockConfig
func (_mock *MockConfig) WatchdogMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WatchdogMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConfig_WatchdogMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchdogMode'
type MockConfig_WatchdogMode_Call struct {
	*mock.Call
}

// WatchdogMode is a helper method to define mock.On call
func (_e *MockConfig_Expecter) WatchdogMode() *MockConfig_WatchdogMode_Call {
	return &MockConfig_WatchdogMode_Call{Call: _e.mock.On("WatchdogMode")}
}

func (_c *MockConfig_WatchdogMode_Call) Run(run func()) *MockConfig_WatchdogMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_WatchdogMode_Call) Return(b bool) *MockConfig_WatchdogMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConfig_WatchdogMode_Call) RunAndReturn(run func() bool) *MockConfig_WatchdogMode_Call {
	_c.Call.Return(run)
	return _c
}
