// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrchestrator creates a new instance of MockOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrchestrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrchestrator {
	mock := &MockOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrchestrator is an autogenerated mock type for the Orchestrator type
type MockOrchestrator struct {
	mock.Mock
}

type MockOrchestrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrchestrator) EXPECT() *MockOrchestrator_Expecter {
	return &MockOrchestrator_Expecter{mock: &_m.Mock}
}

// StartAndWaitForCompletion provides a mock function for the type MockOrchestrator
func (_mock *MockOrchestrator) StartAndWaitForCompletion(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartAndWaitForCompletion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrchestrator_StartAndWaitForCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAndWaitForCompletion'
type MockOrchestrator_StartAndWaitForCompletion_Call struct {
	*mock.Call
}

// StartAndWaitForCompletion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOrchestrator_Expecter) StartAndWaitForCompletion(ctx interface{}) *MockOrchestrator_StartAndWaitForCompletion_Call {
	return &MockOrchestrator_StartAndWaitForCompletion_Call{Call: _e.mock.On("StartAndWaitForCompletion", ctx)}
}

func (_c *MockOrchestrator_StartAndWaitForCompletion_Call) Run(run func(ctx context.Context)) *MockOrchestrator_StartAndWaitForCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOrchestrator_StartAndWaitForCompletion_Call) Return(err error) *MockOrchestrator_StartAndWaitForCompletion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrchestrator_StartAndWaitForCompletion_Call) RunAndReturn(run func(ctx context.Context) error) *MockOrchestrator_StartAndWaitForCompletion_Call {
	_c.Call.Return(run)
	return _c
}
