// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Usage provides a mock function for the type MockParser
func (_mock *MockParser) Usage() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParser_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockParser_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
func (_e *MockParser_Expecter) Usage() *MockParser_Usage_Call {
	return &MockParser_Usage_Call{Call: _e.mock.On("Usage")}
}

func (_c *MockParser_Usage_Call) Run(run func()) *MockParser_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParser_Usage_Call) Return(s string) *MockParser_Usage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParser_Usage_Call) RunAndReturn(run func() string) *MockParser_Usage_Call {
	_c.Call.Return(run)
	return _c
}
