// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWatchdogProcess creates a new instance of MockWatchdogProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchdogProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchdogProcess {
	mock := &MockWatchdogProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchdogProcess is an autogenerated mock type for the WatchdogProcess type
type MockWatchdogProcess struct {
	mock.Mock
}

type MockWatchdogProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchdogProcess) EXPECT() *MockWatchdogProcess_Expecter {
	return &MockWatchdogProcess_Expecter{mock: &_m.Mock}
}

// StartAndWaitForCompletion provides a mock function for the type MockWatchdogProcess
func (_mock *MockWatchdogProcess) StartAndWaitForCompletion(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartAndWaitForCompletion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWatchdogProcess_StartAndWaitForCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAndWaitForCompletion'
type MockWatchdogProcess_StartAndWaitForCompletion_Call struct {
	*mock.Call
}

// StartAndWaitForCompletion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWatchdogProcess_Expecter) StartAndWaitForCompletion(ctx interface{}) *MockWatchdogProcess_StartAndWaitForCompletion_Call {
	return &MockWatchdogProcess_StartAndWaitForCompletion_Call{Call: _e.mock.On("StartAndWaitForCompletion", ctx)}
}

func (_c *MockWatchdogProcess_StartAndWaitForCompletion_Call) Run(run func(ctx context.Context)) *MockWatchdogProcess_StartAndWaitForCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWatchdogProcess_StartAndWaitForCompletion_Call) Return(err error) *MockWatchdogProcess_StartAndWaitForCompletion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWatchdogProcess_StartAndWaitForCompletion_Call) RunAndReturn(run func(ctx context.Context) error) *MockWatchdogProcess_StartAndWaitForCompletion_Call {
	_c.Call.Return(run)
	return _c
}
