// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionIndicator creates a new instance of MockConnectionIndicator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionIndicator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionIndicator {
	mock := &MockConnectionIndicator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionIndicator is an autogenerated mock type for the ConnectionIndicator type
type MockConnectionIndicator struct {
	mock.Mock
}

type MockConnectionIndicator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionIndicator) EXPECT() *MockConnectionIndicator_Expecter {
	return &MockConnectionIndicator_Expecter{mock: &_m.Mock}
}

// ApplyConnectedTitle provides a mock function for the type MockConnectionIndicator
func (_mock *MockConnectionIndicator) ApplyConnectedTitle(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, greetingInfo entities.GreetingInfo) (string, error) {
	ret := _mock.Called(ctx, sessionLogger, client, greetingInfo)

	if len(ret) == 0 {
		panic("no return value specified for ApplyConnectedTitle")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient, entities.GreetingInfo) (string, error)); ok {
		return returnFunc(ctx, sessionLogger, client, greetingInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient, entities.GreetingInfo) string); ok {
		r0 = returnFunc(ctx, sessionLogger, client, greetingInfo)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.MATLABSessionClient, entities.GreetingInfo) error); ok {
		r1 = returnFunc(ctx, sessionLogger, client, greetingInfo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionIndicator_ApplyConnectedTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyConnectedTitle'
type MockConnectionIndicator_ApplyConnectedTitle_Call struct {
	*mock.Call
}

// ApplyConnectedTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - client entities.MATLABSessionClient
//   - greetingInfo entities.GreetingInfo
func (_e *MockConnectionIndicator_Expecter) ApplyConnectedTitle(ctx interface{}, sessionLogger interface{}, client interface{}, greetingInfo interface{}) *MockConnectionIndicator_ApplyConnectedTitle_Call {
	return &MockConnectionIndicator_ApplyConnectedTitle_Call{Call: _e.mock.On("ApplyConnectedTitle", ctx, sessionLogger, client, greetingInfo)}
}

func (_c *MockConnectionIndicator_ApplyConnectedTitle_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, greetingInfo entities.GreetingInfo)) *MockConnectionIndicator_ApplyConnectedTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.MATLABSessionClient
		if args[2] != nil {
			arg2 = args[2].(entities.MATLABSessionClient)
		}
		var arg3 entities.GreetingInfo
		if args[3] != nil {
			arg3 = args[3].(entities.GreetingInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConnectionIndicator_ApplyConnectedTitle_Call) Return(s string, err error) *MockConnectionIndicator_ApplyConnectedTitle_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConnectionIndicator_ApplyConnectedTitle_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, greetingInfo entities.GreetingInfo) (string, error)) *MockConnectionIndicator_ApplyConnectedTitle_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreTitle provides a mock function for the type MockConnectionIndicator
func (_mock *MockConnectionIndicator) RestoreTitle(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, originalTitle string) error {
	ret := _mock.Called(ctx, sessionLogger, client, originalTitle)

	if len(ret) == 0 {
		panic("no return value specified for RestoreTitle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient, string) error); ok {
		r0 = returnFunc(ctx, sessionLogger, client, originalTitle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionIndicator_RestoreTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreTitle'
type MockConnectionIndicator_RestoreTitle_Call struct {
	*mock.Call
}

// RestoreTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - client entities.MATLABSessionClient
//   - originalTitle string
func (_e *MockConnectionIndicator_Expecter) RestoreTitle(ctx interface{}, sessionLogger interface{}, client interface{}, originalTitle interface{}) *MockConnectionIndicator_RestoreTitle_Call {
	return &MockConnectionIndicator_RestoreTitle_Call{Call: _e.mock.On("RestoreTitle", ctx, sessionLogger, client, originalTitle)}
}

func (_c *MockConnectionIndicator_RestoreTitle_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, originalTitle string)) *MockConnectionIndicator_RestoreTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.MATLABSessionClient
		if args[2] != nil {
			arg2 = args[2].(entities.MATLABSessionClient)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConnectionIndicator_RestoreTitle_Call) Return(err error) *MockConnectionIndicator_RestoreTitle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionIndicator_RestoreTitle_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, originalTitle string) error) *MockConnectionIndicator_RestoreTitle_Call {
	_c.Call.Return(run)
	return _c
}

// ShowGreeting provides a mock function for the type MockConnectionIndicator
func (_mock *MockConnectionIndicator) ShowGreeting(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, greetingInfo entities.GreetingInfo) error {
	ret := _mock.Called(ctx, sessionLogger, client, greetingInfo)

	if len(ret) == 0 {
		panic("no return value specified for ShowGreeting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient, entities.GreetingInfo) error); ok {
		r0 = returnFunc(ctx, sessionLogger, client, greetingInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnectionIndicator_ShowGreeting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowGreeting'
type MockConnectionIndicator_ShowGreeting_Call struct {
	*mock.Call
}

// ShowGreeting is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - client entities.MATLABSessionClient
//   - greetingInfo entities.GreetingInfo
func (_e *MockConnectionIndicator_Expecter) ShowGreeting(ctx interface{}, sessionLogger interface{}, client interface{}, greetingInfo interface{}) *MockConnectionIndicator_ShowGreeting_Call {
	return &MockConnectionIndicator_ShowGreeting_Call{Call: _e.mock.On("ShowGreeting", ctx, sessionLogger, client, greetingInfo)}
}

func (_c *MockConnectionIndicator_ShowGreeting_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, greetingInfo entities.GreetingInfo)) *MockConnectionIndicator_ShowGreeting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.MATLABSessionClient
		if args[2] != nil {
			arg2 = args[2].(entities.MATLABSessionClient)
		}
		var arg3 entities.GreetingInfo
		if args[3] != nil {
			arg3 = args[3].(entities.GreetingInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConnectionIndicator_ShowGreeting_Call) Return(err error) *MockConnectionIndicator_ShowGreeting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnectionIndicator_ShowGreeting_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, greetingInfo entities.GreetingInfo) error) *MockConnectionIndicator_ShowGreeting_Call {
	_c.Call.Return(run)
	return _c
}
