// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/datatypes"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionclient/embeddedconnector"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABServices creates a new instance of MockMATLABServices. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABServices(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABServices {
	mock := &MockMATLABServices{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABServices is an autogenerated mock type for the MATLABServices type
type MockMATLABServices struct {
	mock.Mock
}

type MockMATLABServices_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABServices) EXPECT() *MockMATLABServices_Expecter {
	return &MockMATLABServices_Expecter{mock: &_m.Mock}
}

// ListDiscoveredMatlabInfo provides a mock function for the type MockMATLABServices
func (_mock *MockMATLABServices) ListDiscoveredMatlabInfo(logger entities.Logger) datatypes.ListMatlabInfo {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for ListDiscoveredMatlabInfo")
	}

	var r0 datatypes.ListMatlabInfo
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) datatypes.ListMatlabInfo); ok {
		r0 = returnFunc(logger)
	} else {
		r0 = ret.Get(0).(datatypes.ListMatlabInfo)
	}
	return r0
}

// MockMATLABServices_ListDiscoveredMatlabInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDiscoveredMatlabInfo'
type MockMATLABServices_ListDiscoveredMatlabInfo_Call struct {
	*mock.Call
}

// ListDiscoveredMatlabInfo is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockMATLABServices_Expecter) ListDiscoveredMatlabInfo(logger interface{}) *MockMATLABServices_ListDiscoveredMatlabInfo_Call {
	return &MockMATLABServices_ListDiscoveredMatlabInfo_Call{Call: _e.mock.On("ListDiscoveredMatlabInfo", logger)}
}

func (_c *MockMATLABServices_ListDiscoveredMatlabInfo_Call) Run(run func(logger entities.Logger)) *MockMATLABServices_ListDiscoveredMatlabInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABServices_ListDiscoveredMatlabInfo_Call) Return(listMatlabInfo datatypes.ListMatlabInfo) *MockMATLABServices_ListDiscoveredMatlabInfo_Call {
	_c.Call.Return(listMatlabInfo)
	return _c
}

func (_c *MockMATLABServices_ListDiscoveredMatlabInfo_Call) RunAndReturn(run func(logger entities.Logger) datatypes.ListMatlabInfo) *MockMATLABServices_ListDiscoveredMatlabInfo_Call {
	_c.Call.Return(run)
	return _c
}

// StartLocalMATLABSession provides a mock function for the type MockMATLABServices
func (_mock *MockMATLABServices) StartLocalMATLABSession(ctx context.Context, logger entities.Logger, request datatypes.LocalSessionDetails) (embeddedconnector.ConnectionDetails, func() error, error) {
	ret := _mock.Called(ctx, logger, request)

	if len(ret) == 0 {
		panic("no return value specified for StartLocalMATLABSession")
	}

	var r0 embeddedconnector.ConnectionDetails
	var r1 func() error
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, datatypes.LocalSessionDetails) (embeddedconnector.ConnectionDetails, func() error, error)); ok {
		return returnFunc(ctx, logger, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, datatypes.LocalSessionDetails) embeddedconnector.ConnectionDetails); ok {
		r0 = returnFunc(ctx, logger, request)
	} else {
		r0 = ret.Get(0).(embeddedconnector.ConnectionDetails)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, datatypes.LocalSessionDetails) func() error); ok {
		r1 = returnFunc(ctx, logger, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func() error)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.Logger, datatypes.LocalSessionDetails) error); ok {
		r2 = returnFunc(ctx, logger, request)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMATLABServices_StartLocalMATLABSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartLocalMATLABSession'
type MockMATLABServices_StartLocalMATLABSession_Call struct {
	*mock.Call
}

// StartLocalMATLABSession is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
//   - request datatypes.LocalSessionDetails
func (_e *MockMATLABServices_Expecter) StartLocalMATLABSession(ctx interface{}, logger interface{}, request interface{}) *MockMATLABServices_StartLocalMATLABSession_Call {
	return &MockMATLABServices_StartLocalMATLABSession_Call{Call: _e.mock.On("StartLocalMATLABSession", ctx, logger, request)}
}

func (_c *MockMATLABServices_StartLocalMATLABSession_Call) Run(run func(ctx context.Context, logger entities.Logger, request datatypes.LocalSessionDetails)) *MockMATLABServices_StartLocalMATLABSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 datatypes.LocalSessionDetails
		if args[2] != nil {
			arg2 = args[2].(datatypes.LocalSessionDetails)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMATLABServices_StartLocalMATLABSession_Call) Return(connectionDetails embeddedconnector.ConnectionDetails, fn func() error, err error) *MockMATLABServices_StartLocalMATLABSession_Call {
	_c.Call.Return(connectionDetails, fn, err)
	return _c
}

func (_c *MockMATLABServices_StartLocalMATLABSession_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger, request datatypes.LocalSessionDetails) (embeddedconnector.ConnectionDetails, func() error, error)) *MockMATLABServices_StartLocalMATLABSession_Call {
	_c.Call.Return(run)
	return _c
}
