// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMCPClientInfoProvider creates a new instance of MockMCPClientInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMCPClientInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMCPClientInfoProvider {
	mock := &MockMCPClientInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMCPClientInfoProvider is an autogenerated mock type for the MCPClientInfoProvider type
type MockMCPClientInfoProvider struct {
	mock.Mock
}

type MockMCPClientInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMCPClientInfoProvider) EXPECT() *MockMCPClientInfoProvider_Expecter {
	return &MockMCPClientInfoProvider_Expecter{mock: &_m.Mock}
}

// GetClientInfo provides a mock function for the type MockMCPClientInfoProvider
func (_mock *MockMCPClientInfoProvider) GetClientInfo() entities.MCPClientInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientInfo")
	}

	var r0 entities.MCPClientInfo
	if returnFunc, ok := ret.Get(0).(func() entities.MCPClientInfo); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entities.MCPClientInfo)
	}
	return r0
}

// MockMCPClientInfoProvider_GetClientInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientInfo'
type MockMCPClientInfoProvider_GetClientInfo_Call struct {
	*mock.Call
}

// GetClientInfo is a helper method to define mock.On call
func (_e *MockMCPClientInfoProvider_Expecter) GetClientInfo() *MockMCPClientInfoProvider_GetClientInfo_Call {
	return &MockMCPClientInfoProvider_GetClientInfo_Call{Call: _e.mock.On("GetClientInfo")}
}

func (_c *MockMCPClientInfoProvider_GetClientInfo_Call) Run(run func()) *MockMCPClientInfoProvider_GetClientInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMCPClientInfoProvider_GetClientInfo_Call) Return(mCPClientInfo entities.MCPClientInfo) *MockMCPClientInfoProvider_GetClientInfo_Call {
	_c.Call.Return(mCPClientInfo)
	return _c
}

func (_c *MockMCPClientInfoProvider_GetClientInfo_Call) RunAndReturn(run func() entities.MCPClientInfo) *MockMCPClientInfoProvider_GetClientInfo_Call {
	_c.Call.Return(run)
	return _c
}
