// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-server/internal/adaptors/telemetry"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTelemetry creates a new instance of MockTelemetry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetry {
	mock := &MockTelemetry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelemetry is an autogenerated mock type for the Telemetry type
type MockTelemetry struct {
	mock.Mock
}

type MockTelemetry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetry) EXPECT() *MockTelemetry_Expecter {
	return &MockTelemetry_Expecter{mock: &_m.Mock}
}

// RecordClientConnection provides a mock function for the type MockTelemetry
func (_mock *MockTelemetry) RecordClientConnection(ctx context.Context, info telemetry.ClientConnectionInfo) {
	_mock.Called(ctx, info)
	return
}

// MockTelemetry_RecordClientConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordClientConnection'
type MockTelemetry_RecordClientConnection_Call struct {
	*mock.Call
}

// RecordClientConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - info telemetry.ClientConnectionInfo
func (_e *MockTelemetry_Expecter) RecordClientConnection(ctx interface{}, info interface{}) *MockTelemetry_RecordClientConnection_Call {
	return &MockTelemetry_RecordClientConnection_Call{Call: _e.mock.On("RecordClientConnection", ctx, info)}
}

func (_c *MockTelemetry_RecordClientConnection_Call) Run(run func(ctx context.Context, info telemetry.ClientConnectionInfo)) *MockTelemetry_RecordClientConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 telemetry.ClientConnectionInfo
		if args[1] != nil {
			arg1 = args[1].(telemetry.ClientConnectionInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTelemetry_RecordClientConnection_Call) Return() *MockTelemetry_RecordClientConnection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetry_RecordClientConnection_Call) RunAndReturn(run func(ctx context.Context, info telemetry.ClientConnectionInfo)) *MockTelemetry_RecordClientConnection_Call {
	_c.Run(run)
	return _c
}

// RecordServerStart provides a mock function for the type MockTelemetry
func (_mock *MockTelemetry) RecordServerStart(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockTelemetry_RecordServerStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordServerStart'
type MockTelemetry_RecordServerStart_Call struct {
	*mock.Call
}

// RecordServerStart is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTelemetry_Expecter) RecordServerStart(ctx interface{}) *MockTelemetry_RecordServerStart_Call {
	return &MockTelemetry_RecordServerStart_Call{Call: _e.mock.On("RecordServerStart", ctx)}
}

func (_c *MockTelemetry_RecordServerStart_Call) Run(run func(ctx context.Context)) *MockTelemetry_RecordServerStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTelemetry_RecordServerStart_Call) Return() *MockTelemetry_RecordServerStart_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetry_RecordServerStart_Call) RunAndReturn(run func(ctx context.Context)) *MockTelemetry_RecordServerStart_Call {
	_c.Run(run)
	return _c
}

// RecordToolCallRequest provides a mock function for the type MockTelemetry
func (_mock *MockTelemetry) RecordToolCallRequest(ctx context.Context, toolName string, source telemetry.ToolSource) {
	_mock.Called(ctx, toolName, source)
	return
}

// MockTelemetry_RecordToolCallRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordToolCallRequest'
type MockTelemetry_RecordToolCallRequest_Call struct {
	*mock.Call
}

// RecordToolCallRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - toolName string
//   - source telemetry.ToolSource
func (_e *MockTelemetry_Expecter) RecordToolCallRequest(ctx interface{}, toolName interface{}, source interface{}) *MockTelemetry_RecordToolCallRequest_Call {
	return &MockTelemetry_RecordToolCallRequest_Call{Call: _e.mock.On("RecordToolCallRequest", ctx, toolName, source)}
}

func (_c *MockTelemetry_RecordToolCallRequest_Call) Run(run func(ctx context.Context, toolName string, source telemetry.ToolSource)) *MockTelemetry_RecordToolCallRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 telemetry.ToolSource
		if args[2] != nil {
			arg2 = args[2].(telemetry.ToolSource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTelemetry_RecordToolCallRequest_Call) Return() *MockTelemetry_RecordToolCallRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetry_RecordToolCallRequest_Call) RunAndReturn(run func(ctx context.Context, toolName string, source telemetry.ToolSource)) *MockTelemetry_RecordToolCallRequest_Call {
	_c.Run(run)
	return _c
}
