// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/http/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHTTPClientFactory creates a new instance of MockHTTPClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClientFactory {
	mock := &MockHTTPClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPClientFactory is an autogenerated mock type for the HTTPClientFactory type
type MockHTTPClientFactory struct {
	mock.Mock
}

type MockHTTPClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClientFactory) EXPECT() *MockHTTPClientFactory_Expecter {
	return &MockHTTPClientFactory_Expecter{mock: &_m.Mock}
}

// NewClientOverUDS provides a mock function for the type MockHTTPClientFactory
func (_mock *MockHTTPClientFactory) NewClientOverUDS(socketPath string) client.HttpClient {
	ret := _mock.Called(socketPath)

	if len(ret) == 0 {
		panic("no return value specified for NewClientOverUDS")
	}

	var r0 client.HttpClient
	if returnFunc, ok := ret.Get(0).(func(string) client.HttpClient); ok {
		r0 = returnFunc(socketPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.HttpClient)
		}
	}
	return r0
}

// MockHTTPClientFactory_NewClientOverUDS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClientOverUDS'
type MockHTTPClientFactory_NewClientOverUDS_Call struct {
	*mock.Call
}

// NewClientOverUDS is a helper method to define mock.On call
//   - socketPath string
func (_e *MockHTTPClientFactory_Expecter) NewClientOverUDS(socketPath interface{}) *MockHTTPClientFactory_NewClientOverUDS_Call {
	return &MockHTTPClientFactory_NewClientOverUDS_Call{Call: _e.mock.On("NewClientOverUDS", socketPath)}
}

func (_c *MockHTTPClientFactory_NewClientOverUDS_Call) Run(run func(socketPath string)) *MockHTTPClientFactory_NewClientOverUDS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHTTPClientFactory_NewClientOverUDS_Call) Return(httpClient client.HttpClient) *MockHTTPClientFactory_NewClientOverUDS_Call {
	_c.Call.Return(httpClient)
	return _c
}

func (_c *MockHTTPClientFactory_NewClientOverUDS_Call) RunAndReturn(run func(socketPath string) client.HttpClient) *MockHTTPClientFactory_NewClientOverUDS_Call {
	_c.Call.Return(run)
	return _c
}
