// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/http/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHttpClientFactory creates a new instance of MockHttpClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHttpClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHttpClientFactory {
	mock := &MockHttpClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHttpClientFactory is an autogenerated mock type for the HttpClientFactory type
type MockHttpClientFactory struct {
	mock.Mock
}

type MockHttpClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHttpClientFactory) EXPECT() *MockHttpClientFactory_Expecter {
	return &MockHttpClientFactory_Expecter{mock: &_m.Mock}
}

// NewClientForSelfSignedTLSServer provides a mock function for the type MockHttpClientFactory
func (_mock *MockHttpClientFactory) NewClientForSelfSignedTLSServer(certificatePEM []byte) (client.HttpClient, error) {
	ret := _mock.Called(certificatePEM)

	if len(ret) == 0 {
		panic("no return value specified for NewClientForSelfSignedTLSServer")
	}

	var r0 client.HttpClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (client.HttpClient, error)); ok {
		return returnFunc(certificatePEM)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) client.HttpClient); ok {
		r0 = returnFunc(certificatePEM)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.HttpClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(certificatePEM)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClientForSelfSignedTLSServer'
type MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call struct {
	*mock.Call
}

// NewClientForSelfSignedTLSServer is a helper method to define mock.On call
//   - certificatePEM []byte
func (_e *MockHttpClientFactory_Expecter) NewClientForSelfSignedTLSServer(certificatePEM interface{}) *MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call {
	return &MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call{Call: _e.mock.On("NewClientForSelfSignedTLSServer", certificatePEM)}
}

func (_c *MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call) Run(run func(certificatePEM []byte)) *MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call) Return(httpClient client.HttpClient, err error) *MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call {
	_c.Call.Return(httpClient, err)
	return _c
}

func (_c *MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call) RunAndReturn(run func(certificatePEM []byte) (client.HttpClient, error)) *MockHttpClientFactory_NewClientForSelfSignedTLSServer_Call {
	_c.Call.Return(run)
	return _c
}
