# Copyright 2025 The MathWorks, Inc.

all: true
filename: '{{.InterfaceName}}.go'
pkgname: 'mocks'
packages:
  github.com/matlab/matlab-mcp-core-server/internal:
    config:
      dir: 'mocks/{{.InterfaceDirRelative | trimPrefix "internal" }}'
      recursive: true
      all: true
  github.com/matlab/matlab-mcp-core-server/tests/testutils:
    config:
      dir: 'tests/mocks/{{.InterfaceDirRelative | trimPrefix "tests" }}'
      recursive: true
      all: true
