// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/config"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/directory"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/inputs/parser"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/lifecyclesignaler"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/modeselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/orchestrator"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/filesystem/files"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab/matlabrootselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/globalmatlab/matlabstartingdirselector"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/logger"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession"
	directory2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/directory"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/directory/matlabfiles"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/processdetails"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/processlauncher"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator/matlabroot"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/matlablocator/matlabversion"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionclient"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionstore"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/resources/codingguidelines"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/resources/plaintextlivecodegeneration"
	server2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/server"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/server/configurator"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/server/sdk"
	evalmatlabcode2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/evalmatlabcode"
	listavailablematlabs2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/listavailablematlabs"
	startmatlabsession2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/startmatlabsession"
	stopmatlabsession2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/multisession/stopmatlabsession"
	checkmatlabcode2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/checkmatlabcode"
	detectmatlabtoolboxes2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/detectmatlabtoolboxes"
	evalmatlabcode3 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/evalmatlabcode"
	runmatlabfile2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/runmatlabfile"
	runmatlabtestfile2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools/singlesession/runmatlabtestfile"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/messagecatalog"
	watchdog2 "github.com/matlab/matlab-mcp-core-server/internal/adaptors/watchdog"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/watchdog/process"
	"github.com/matlab/matlab-mcp-core-server/internal/facades/filefacade"
	"github.com/matlab/matlab-mcp-core-server/internal/facades/iofacade"
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/checkmatlabcode"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/detectmatlabtoolboxes"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/evalmatlabcode"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/listavailablematlabs"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/runmatlabfile"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/runmatlabtestfile"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/startmatlabsession"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/stopmatlabsession"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/utils/pathvalidator"
	"github.com/matlab/matlab-mcp-core-server/internal/utils/httpclientfactory"
	"github.com/matlab/matlab-mcp-core-server/internal/utils/httpserverfactory"
	"github.com/matlab/matlab-mcp-core-server/internal/utils/ossignaler"
	"github.com/matlab/matlab-mcp-core-server/internal/utils/oswrapper"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/processhandler"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/client"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/server"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/server/handler"
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/socket"
)

// Injectors from wire.go:

func Initialize() *Application {
	messageCatalog := messagecatalog.New()
	parserParser := parser.New(messageCatalog)
	osFacade := osfacade.New()
	factory := config.NewFactory(parserParser, osFacade)
	filesFactory := files.NewFactory(osFacade)
	directoryFactory := directory.NewFactory(factory, filesFactory, osFacade)
	loggerFactory := logger.NewFactory(factory, directoryFactory, filesFactory, osFacade)
	osWrapper := oswrapper.New(osFacade)
	processHandler := processhandler.New(loggerFactory, osWrapper)
	osSignaler := ossignaler.New()
	handlerFactory := handler.NewFactory(loggerFactory, processHandler)
	httpServerFactory := httpserverfactory.New(osFacade)
	serverFactory := server.NewFactory(httpServerFactory, loggerFactory, handlerFactory)
	socketFactory := socket.NewFactory(directoryFactory, osFacade)
	watchdogWatchdog := watchdog.New(loggerFactory, osFacade, processHandler, osSignaler, handlerFactory, serverFactory, socketFactory)
	lifecycleSignaler := lifecyclesignaler.New()
	sdkFactory := sdk.NewFactory(factory)
	fileFacade := filefacade.New()
	getter := matlabroot.New(osFacade, fileFacade)
	ioFacade := iofacade.New()
	matlabversionGetter := matlabversion.New(osFacade, ioFacade)
	matlabLocator := matlablocator.New(getter, matlabversionGetter)
	matlabFiles := matlabfiles.New()
	factory2 := directory2.NewFactory(osFacade, directoryFactory, matlabFiles)
	processDetails := processdetails.New(osFacade)
	matlabProcessLauncher := processlauncher.New()
	processFactory := process.New(osFacade, loggerFactory, directoryFactory, factory)
	httpClientFactory := httpclientfactory.New()
	clientFactory := client.NewFactory(osFacade, loggerFactory, httpClientFactory)
	watchdog3 := watchdog2.New(processFactory, clientFactory, loggerFactory, socketFactory)
	starter := localmatlabsession.NewStarter(factory2, processDetails, matlabProcessLauncher, watchdog3)
	matlabServices := matlabservices.New(matlabLocator, starter)
	store := matlabsessionstore.New(loggerFactory, lifecycleSignaler)
	matlabsessionclientFactory := matlabsessionclient.NewFactory(httpClientFactory)
	matlabManager := matlabmanager.New(matlabServices, store, matlabsessionclientFactory)
	usecase := listavailablematlabs.New(matlabManager)
	tool := listavailablematlabs2.New(loggerFactory, usecase)
	startmatlabsessionUsecase := startmatlabsession.New(matlabManager)
	startmatlabsessionTool := startmatlabsession2.New(loggerFactory, startmatlabsessionUsecase)
	stopmatlabsessionUsecase := stopmatlabsession.New(matlabManager)
	stopmatlabsessionTool := stopmatlabsession2.New(loggerFactory, stopmatlabsessionUsecase)
	pathValidator := pathvalidator.New(osFacade)
	evalmatlabcodeUsecase := evalmatlabcode.New(pathValidator)
	evalmatlabcodeTool := evalmatlabcode2.New(loggerFactory, evalmatlabcodeUsecase, matlabManager)
	matlabRootSelector := matlabrootselector.New(factory, matlabManager)
	matlabStartingDirSelector := matlabstartingdirselector.New(factory, osFacade)
	globalMATLAB := globalmatlab.New(matlabManager, matlabRootSelector, matlabStartingDirSelector)
	tool2 := evalmatlabcode3.New(loggerFactory, evalmatlabcodeUsecase, globalMATLAB)
	checkmatlabcodeUsecase := checkmatlabcode.New(pathValidator)
	checkmatlabcodeTool := checkmatlabcode2.New(loggerFactory, checkmatlabcodeUsecase, globalMATLAB)
	detectmatlabtoolboxesUsecase := detectmatlabtoolboxes.New()
	detectmatlabtoolboxesTool := detectmatlabtoolboxes2.New(loggerFactory, detectmatlabtoolboxesUsecase, globalMATLAB)
	runmatlabfileUsecase := runmatlabfile.New(pathValidator)
	runmatlabfileTool := runmatlabfile2.New(loggerFactory, runmatlabfileUsecase, globalMATLAB)
	runmatlabtestfileUsecase := runmatlabtestfile.New(pathValidator)
	runmatlabtestfileTool := runmatlabtestfile2.New(loggerFactory, runmatlabtestfileUsecase, globalMATLAB)
	resource := codingguidelines.New(loggerFactory)
	plaintextlivecodegenerationResource := plaintextlivecodegeneration.New(loggerFactory)
	configuratorConfigurator := configurator.New(factory, tool, startmatlabsessionTool, stopmatlabsessionTool, evalmatlabcodeTool, tool2, checkmatlabcodeTool, detectmatlabtoolboxesTool, runmatlabfileTool, runmatlabtestfileTool, resource, plaintextlivecodegenerationResource)
	serverServer := server2.New(sdkFactory, loggerFactory, lifecycleSignaler, configuratorConfigurator)
	orchestratorOrchestrator := orchestrator.New(lifecycleSignaler, factory, serverServer, watchdog3, loggerFactory, osSignaler, globalMATLAB, directoryFactory)
	modeSelector := modeselector.New(factory, parserParser, watchdogWatchdog, orchestratorOrchestrator, osFacade)
	application := &Application{
		ModeSelector:      modeSelector,
		MessageCatalog:    messageCatalog,
		HTTPClientFactory: httpClientFactory,
		HTTPServerFactory: httpServerFactory,
	}
	return application
}

// wire.go:

type Application struct {
	ModeSelector      *modeselector.ModeSelector
	MessageCatalog    *messagecatalog.MessageCatalog
	HTTPClientFactory *httpclientfactory.HTTPClientFactory
	HTTPServerFactory *httpserverfactory.HTTPServerFactory
}
