// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWatchdogProcess creates a new instance of MockWatchdogProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchdogProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchdogProcess {
	mock := &MockWatchdogProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchdogProcess is an autogenerated mock type for the WatchdogProcess type
type MockWatchdogProcess struct {
	mock.Mock
}

type MockWatchdogProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchdogProcess) EXPECT() *MockWatchdogProcess_Expecter {
	return &MockWatchdogProcess_Expecter{mock: &_m.Mock}
}

// StartNewProcess provides a mock function for the type MockWatchdogProcess
func (_mock *MockWatchdogProcess) StartNewProcess() messages.Error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartNewProcess")
	}

	var r0 messages.Error
	if returnFunc, ok := ret.Get(0).(func() messages.Error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.Error)
		}
	}
	return r0
}

// MockWatchdogProcess_StartNewProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartNewProcess'
type MockWatchdogProcess_StartNewProcess_Call struct {
	*mock.Call
}

// StartNewProcess is a helper method to define mock.On call
func (_e *MockWatchdogProcess_Expecter) StartNewProcess() *MockWatchdogProcess_StartNewProcess_Call {
	return &MockWatchdogProcess_StartNewProcess_Call{Call: _e.mock.On("StartNewProcess")}
}

func (_c *MockWatchdogProcess_StartNewProcess_Call) Run(run func()) *MockWatchdogProcess_StartNewProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatchdogProcess_StartNewProcess_Call) Return(error messages.Error) *MockWatchdogProcess_StartNewProcess_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *MockWatchdogProcess_StartNewProcess_Call) RunAndReturn(run func() messages.Error) *MockWatchdogProcess_StartNewProcess_Call {
	_c.Call.Return(run)
	return _c
}
