// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/resources"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResource creates a new instance of MockResource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResource {
	mock := &MockResource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResource is an autogenerated mock type for the Resource type
type MockResource struct {
	mock.Mock
}

type MockResource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResource) EXPECT() *MockResource_Expecter {
	return &MockResource_Expecter{mock: &_m.Mock}
}

// AddToServer provides a mock function for the type MockResource
func (_mock *MockResource) AddToServer(server resources.Server) error {
	ret := _mock.Called(server)

	if len(ret) == 0 {
		panic("no return value specified for AddToServer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(resources.Server) error); ok {
		r0 = returnFunc(server)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResource_AddToServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToServer'
type MockResource_AddToServer_Call struct {
	*mock.Call
}

// AddToServer is a helper method to define mock.On call
//   - server resources.Server
func (_e *MockResource_Expecter) AddToServer(server interface{}) *MockResource_AddToServer_Call {
	return &MockResource_AddToServer_Call{Call: _e.mock.On("AddToServer", server)}
}

func (_c *MockResource_AddToServer_Call) Run(run func(server resources.Server)) *MockResource_AddToServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 resources.Server
		if args[0] != nil {
			arg0 = args[0].(resources.Server)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResource_AddToServer_Call) Return(err error) *MockResource_AddToServer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResource_AddToServer_Call) RunAndReturn(run func(server resources.Server) error) *MockResource_AddToServer_Call {
	_c.Call.Return(run)
	return _c
}
