// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/directory"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplicationDirectoryFactory creates a new instance of MockApplicationDirectoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplicationDirectoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplicationDirectoryFactory {
	mock := &MockApplicationDirectoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplicationDirectoryFactory is an autogenerated mock type for the ApplicationDirectoryFactory type
type MockApplicationDirectoryFactory struct {
	mock.Mock
}

type MockApplicationDirectoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplicationDirectoryFactory) EXPECT() *MockApplicationDirectoryFactory_Expecter {
	return &MockApplicationDirectoryFactory_Expecter{mock: &_m.Mock}
}

// Directory provides a mock function for the type MockApplicationDirectoryFactory
func (_mock *MockApplicationDirectoryFactory) Directory() (directory.Directory, messages.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Directory")
	}

	var r0 directory.Directory
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func() (directory.Directory, messages.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() directory.Directory); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(directory.Directory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() messages.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockApplicationDirectoryFactory_Directory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Directory'
type MockApplicationDirectoryFactory_Directory_Call struct {
	*mock.Call
}

// Directory is a helper method to define mock.On call
func (_e *MockApplicationDirectoryFactory_Expecter) Directory() *MockApplicationDirectoryFactory_Directory_Call {
	return &MockApplicationDirectoryFactory_Directory_Call{Call: _e.mock.On("Directory")}
}

func (_c *MockApplicationDirectoryFactory_Directory_Call) Run(run func()) *MockApplicationDirectoryFactory_Directory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplicationDirectoryFactory_Directory_Call) Return(directory1 directory.Directory, error messages.Error) *MockApplicationDirectoryFactory_Directory_Call {
	_c.Call.Return(directory1, error)
	return _c
}

func (_c *MockApplicationDirectoryFactory_Directory_Call) RunAndReturn(run func() (directory.Directory, messages.Error)) *MockApplicationDirectoryFactory_Directory_Call {
	_c.Call.Return(run)
	return _c
}
