// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDirectory creates a new instance of MockDirectory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirectory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirectory {
	mock := &MockDirectory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDirectory is an autogenerated mock type for the Directory type
type MockDirectory struct {
	mock.Mock
}

type MockDirectory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirectory) EXPECT() *MockDirectory_Expecter {
	return &MockDirectory_Expecter{mock: &_m.Mock}
}

// CertificateFile provides a mock function for the type MockDirectory
func (_mock *MockDirectory) CertificateFile() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificateFile")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDirectory_CertificateFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateFile'
type MockDirectory_CertificateFile_Call struct {
	*mock.Call
}

// CertificateFile is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) CertificateFile() *MockDirectory_CertificateFile_Call {
	return &MockDirectory_CertificateFile_Call{Call: _e.mock.On("CertificateFile")}
}

func (_c *MockDirectory_CertificateFile_Call) Run(run func()) *MockDirectory_CertificateFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_CertificateFile_Call) Return(s string) *MockDirectory_CertificateFile_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDirectory_CertificateFile_Call) RunAndReturn(run func() string) *MockDirectory_CertificateFile_Call {
	_c.Call.Return(run)
	return _c
}

// CertificateKeyFile provides a mock function for the type MockDirectory
func (_mock *MockDirectory) CertificateKeyFile() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CertificateKeyFile")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDirectory_CertificateKeyFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateKeyFile'
type MockDirectory_CertificateKeyFile_Call struct {
	*mock.Call
}

// CertificateKeyFile is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) CertificateKeyFile() *MockDirectory_CertificateKeyFile_Call {
	return &MockDirectory_CertificateKeyFile_Call{Call: _e.mock.On("CertificateKeyFile")}
}

func (_c *MockDirectory_CertificateKeyFile_Call) Run(run func()) *MockDirectory_CertificateKeyFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_CertificateKeyFile_Call) Return(s string) *MockDirectory_CertificateKeyFile_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDirectory_CertificateKeyFile_Call) RunAndReturn(run func() string) *MockDirectory_CertificateKeyFile_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function for the type MockDirectory
func (_mock *MockDirectory) Cleanup() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDirectory_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockDirectory_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) Cleanup() *MockDirectory_Cleanup_Call {
	return &MockDirectory_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *MockDirectory_Cleanup_Call) Run(run func()) *MockDirectory_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_Cleanup_Call) Return(err error) *MockDirectory_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDirectory_Cleanup_Call) RunAndReturn(run func() error) *MockDirectory_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// GetEmbeddedConnectorDetails provides a mock function for the type MockDirectory
func (_mock *MockDirectory) GetEmbeddedConnectorDetails() (string, []byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEmbeddedConnectorDetails")
	}

	var r0 string
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, []byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() []byte); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDirectory_GetEmbeddedConnectorDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEmbeddedConnectorDetails'
type MockDirectory_GetEmbeddedConnectorDetails_Call struct {
	*mock.Call
}

// GetEmbeddedConnectorDetails is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) GetEmbeddedConnectorDetails() *MockDirectory_GetEmbeddedConnectorDetails_Call {
	return &MockDirectory_GetEmbeddedConnectorDetails_Call{Call: _e.mock.On("GetEmbeddedConnectorDetails")}
}

func (_c *MockDirectory_GetEmbeddedConnectorDetails_Call) Run(run func()) *MockDirectory_GetEmbeddedConnectorDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_GetEmbeddedConnectorDetails_Call) Return(s string, bytes []byte, err error) *MockDirectory_GetEmbeddedConnectorDetails_Call {
	_c.Call.Return(s, bytes, err)
	return _c
}

func (_c *MockDirectory_GetEmbeddedConnectorDetails_Call) RunAndReturn(run func() (string, []byte, error)) *MockDirectory_GetEmbeddedConnectorDetails_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function for the type MockDirectory
func (_mock *MockDirectory) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDirectory_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockDirectory_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) Path() *MockDirectory_Path_Call {
	return &MockDirectory_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *MockDirectory_Path_Call) Run(run func()) *MockDirectory_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_Path_Call) Return(s string) *MockDirectory_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDirectory_Path_Call) RunAndReturn(run func() string) *MockDirectory_Path_Call {
	_c.Call.Return(run)
	return _c
}
