// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABFiles creates a new instance of MockMATLABFiles. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABFiles(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABFiles {
	mock := &MockMATLABFiles{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABFiles is an autogenerated mock type for the MATLABFiles type
type MockMATLABFiles struct {
	mock.Mock
}

type MockMATLABFiles_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABFiles) EXPECT() *MockMATLABFiles_Expecter {
	return &MockMATLABFiles_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockMATLABFiles
func (_mock *MockMATLABFiles) GetAll() map[string][]byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string][]byte
	if returnFunc, ok := ret.Get(0).(func() map[string][]byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	return r0
}

// MockMATLABFiles_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockMATLABFiles_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockMATLABFiles_Expecter) GetAll() *MockMATLABFiles_GetAll_Call {
	return &MockMATLABFiles_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockMATLABFiles_GetAll_Call) Run(run func()) *MockMATLABFiles_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMATLABFiles_GetAll_Call) Return(stringToBytes map[string][]byte) *MockMATLABFiles_GetAll_Call {
	_c.Call.Return(stringToBytes)
	return _c
}

func (_c *MockMATLABFiles_GetAll_Call) RunAndReturn(run func() map[string][]byte) *MockMATLABFiles_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
