// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// Mkdir provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Mkdir(name string, perm os.FileMode) error {
	ret := _mock.Called(name, perm)

	if len(ret) == 0 {
		panic("no return value specified for Mkdir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(name, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOSLayer_Mkdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mkdir'
type MockOSLayer_Mkdir_Call struct {
	*mock.Call
}

// Mkdir is a helper method to define mock.On call
//   - name string
//   - perm os.FileMode
func (_e *MockOSLayer_Expecter) Mkdir(name interface{}, perm interface{}) *MockOSLayer_Mkdir_Call {
	return &MockOSLayer_Mkdir_Call{Call: _e.mock.On("Mkdir", name, perm)}
}

func (_c *MockOSLayer_Mkdir_Call) Run(run func(name string, perm os.FileMode)) *MockOSLayer_Mkdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOSLayer_Mkdir_Call) Return(err error) *MockOSLayer_Mkdir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOSLayer_Mkdir_Call) RunAndReturn(run func(name string, perm os.FileMode) error) *MockOSLayer_Mkdir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) ReadFile(filePath string) ([]byte, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSLayer_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockOSLayer_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - filePath string
func (_e *MockOSLayer_Expecter) ReadFile(filePath interface{}) *MockOSLayer_ReadFile_Call {
	return &MockOSLayer_ReadFile_Call{Call: _e.mock.On("ReadFile", filePath)}
}

func (_c *MockOSLayer_ReadFile_Call) Run(run func(filePath string)) *MockOSLayer_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_ReadFile_Call) Return(bytes []byte, err error) *MockOSLayer_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockOSLayer_ReadFile_Call) RunAndReturn(run func(filePath string) ([]byte, error)) *MockOSLayer_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) RemoveAll(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOSLayer_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockOSLayer_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *MockOSLayer_Expecter) RemoveAll(path interface{}) *MockOSLayer_RemoveAll_Call {
	return &MockOSLayer_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *MockOSLayer_RemoveAll_Call) Run(run func(path string)) *MockOSLayer_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_RemoveAll_Call) Return(err error) *MockOSLayer_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOSLayer_RemoveAll_Call) RunAndReturn(run func(path string) error) *MockOSLayer_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Stat(name string) (osfacade.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 osfacade.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (osfacade.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) osfacade.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSLayer_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockOSLayer_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *MockOSLayer_Expecter) Stat(name interface{}) *MockOSLayer_Stat_Call {
	return &MockOSLayer_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockOSLayer_Stat_Call) Run(run func(name string)) *MockOSLayer_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_Stat_Call) Return(fileInfo osfacade.FileInfo, err error) *MockOSLayer_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockOSLayer_Stat_Call) RunAndReturn(run func(name string) (osfacade.FileInfo, error)) *MockOSLayer_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) WriteFile(name string, data []byte, perm os.FileMode) error {
	ret := _mock.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = returnFunc(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOSLayer_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockOSLayer_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name string
//   - data []byte
//   - perm os.FileMode
func (_e *MockOSLayer_Expecter) WriteFile(name interface{}, data interface{}, perm interface{}) *MockOSLayer_WriteFile_Call {
	return &MockOSLayer_WriteFile_Call{Call: _e.mock.On("WriteFile", name, data, perm)}
}

func (_c *MockOSLayer_WriteFile_Call) Run(run func(name string, data []byte, perm os.FileMode)) *MockOSLayer_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 os.FileMode
		if args[2] != nil {
			arg2 = args[2].(os.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOSLayer_WriteFile_Call) Return(err error) *MockOSLayer_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOSLayer_WriteFile_Call) RunAndReturn(run func(name string, data []byte, perm os.FileMode) error) *MockOSLayer_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
