// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHttpServer creates a new instance of MockHttpServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHttpServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHttpServer {
	mock := &MockHttpServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHttpServer is an autogenerated mock type for the HttpServer type
type MockHttpServer struct {
	mock.Mock
}

type MockHttpServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHttpServer) EXPECT() *MockHttpServer_Expecter {
	return &MockHttpServer_Expecter{mock: &_m.Mock}
}

// Serve provides a mock function for the type MockHttpServer
func (_mock *MockHttpServer) Serve(socketPath string) error {
	ret := _mock.Called(socketPath)

	if len(ret) == 0 {
		panic("no return value specified for Serve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(socketPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHttpServer_Serve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serve'
type MockHttpServer_Serve_Call struct {
	*mock.Call
}

// Serve is a helper method to define mock.On call
//   - socketPath string
func (_e *MockHttpServer_Expecter) Serve(socketPath interface{}) *MockHttpServer_Serve_Call {
	return &MockHttpServer_Serve_Call{Call: _e.mock.On("Serve", socketPath)}
}

func (_c *MockHttpServer_Serve_Call) Run(run func(socketPath string)) *MockHttpServer_Serve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHttpServer_Serve_Call) Return(err error) *MockHttpServer_Serve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHttpServer_Serve_Call) RunAndReturn(run func(socketPath string) error) *MockHttpServer_Serve_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockHttpServer
func (_mock *MockHttpServer) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHttpServer_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockHttpServer_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHttpServer_Expecter) Shutdown(ctx interface{}) *MockHttpServer_Shutdown_Call {
	return &MockHttpServer_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockHttpServer_Shutdown_Call) Run(run func(ctx context.Context)) *MockHttpServer_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHttpServer_Shutdown_Call) Return(err error) *MockHttpServer_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHttpServer_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockHttpServer_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
