// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// RemoveAll provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) RemoveAll(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOSLayer_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type MockOSLayer_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - name string
func (_e *MockOSLayer_Expecter) RemoveAll(name interface{}) *MockOSLayer_RemoveAll_Call {
	return &MockOSLayer_RemoveAll_Call{Call: _e.mock.On("RemoveAll", name)}
}

func (_c *MockOSLayer_RemoveAll_Call) Run(run func(name string)) *MockOSLayer_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_RemoveAll_Call) Return(err error) *MockOSLayer_RemoveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOSLayer_RemoveAll_Call) RunAndReturn(run func(name string) error) *MockOSLayer_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}
