// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdditionalToolsProvider creates a new instance of MockAdditionalToolsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdditionalToolsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdditionalToolsProvider {
	mock := &MockAdditionalToolsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdditionalToolsProvider is an autogenerated mock type for the AdditionalToolsProvider type
type MockAdditionalToolsProvider struct {
	mock.Mock
}

type MockAdditionalToolsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdditionalToolsProvider) EXPECT() *MockAdditionalToolsProvider_Expecter {
	return &MockAdditionalToolsProvider_Expecter{mock: &_m.Mock}
}

// Tools provides a mock function for the type MockAdditionalToolsProvider
func (_mock *MockAdditionalToolsProvider) Tools(loggerFactory definition.LoggerFactory) []tools.Tool {
	ret := _mock.Called(loggerFactory)

	if len(ret) == 0 {
		panic("no return value specified for Tools")
	}

	var r0 []tools.Tool
	if returnFunc, ok := ret.Get(0).(func(definition.LoggerFactory) []tools.Tool); ok {
		r0 = returnFunc(loggerFactory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tools.Tool)
		}
	}
	return r0
}

// MockAdditionalToolsProvider_Tools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tools'
type MockAdditionalToolsProvider_Tools_Call struct {
	*mock.Call
}

// Tools is a helper method to define mock.On call
//   - loggerFactory definition.LoggerFactory
func (_e *MockAdditionalToolsProvider_Expecter) Tools(loggerFactory interface{}) *MockAdditionalToolsProvider_Tools_Call {
	return &MockAdditionalToolsProvider_Tools_Call{Call: _e.mock.On("Tools", loggerFactory)}
}

func (_c *MockAdditionalToolsProvider_Tools_Call) Run(run func(loggerFactory definition.LoggerFactory)) *MockAdditionalToolsProvider_Tools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 definition.LoggerFactory
		if args[0] != nil {
			arg0 = args[0].(definition.LoggerFactory)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdditionalToolsProvider_Tools_Call) Return(tools1 []tools.Tool) *MockAdditionalToolsProvider_Tools_Call {
	_c.Call.Return(tools1)
	return _c
}

func (_c *MockAdditionalToolsProvider_Tools_Call) RunAndReturn(run func(loggerFactory definition.LoggerFactory) []tools.Tool) *MockAdditionalToolsProvider_Tools_Call {
	_c.Call.Return(run)
	return _c
}
