// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMCPSDKServerFactory creates a new instance of MockMCPSDKServerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMCPSDKServerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMCPSDKServerFactory {
	mock := &MockMCPSDKServerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMCPSDKServerFactory is an autogenerated mock type for the MCPSDKServerFactory type
type MockMCPSDKServerFactory struct {
	mock.Mock
}

type MockMCPSDKServerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMCPSDKServerFactory) EXPECT() *MockMCPSDKServerFactory_Expecter {
	return &MockMCPSDKServerFactory_Expecter{mock: &_m.Mock}
}

// NewServer provides a mock function for the type MockMCPSDKServerFactory
func (_mock *MockMCPSDKServerFactory) NewServer() (*mcp.Server, messages.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewServer")
	}

	var r0 *mcp.Server
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func() (*mcp.Server, messages.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *mcp.Server); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.Server)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() messages.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockMCPSDKServerFactory_NewServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewServer'
type MockMCPSDKServerFactory_NewServer_Call struct {
	*mock.Call
}

// NewServer is a helper method to define mock.On call
func (_e *MockMCPSDKServerFactory_Expecter) NewServer() *MockMCPSDKServerFactory_NewServer_Call {
	return &MockMCPSDKServerFactory_NewServer_Call{Call: _e.mock.On("NewServer")}
}

func (_c *MockMCPSDKServerFactory_NewServer_Call) Run(run func()) *MockMCPSDKServerFactory_NewServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMCPSDKServerFactory_NewServer_Call) Return(server *mcp.Server, error messages.Error) *MockMCPSDKServerFactory_NewServer_Call {
	_c.Call.Return(server, error)
	return _c
}

func (_c *MockMCPSDKServerFactory_NewServer_Call) RunAndReturn(run func() (*mcp.Server, messages.Error)) *MockMCPSDKServerFactory_NewServer_Call {
	_c.Call.Return(run)
	return _c
}
