classdef CreatePermissionManagerTest < matlab.mock.TestCase
    %CreatePermissionManagerTest Tests for createPermissionManager factory.
    %   Asserts that the factory returns the platform-appropriate concrete
    %   PermissionManager and that no Windows-only class is selected on
    %   non-Windows platforms.
    %
    %   The OSFacade is mocked, so the test runs identically on every
    %   platform and exercises both branches.

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testCreatePermissionManager_OnNonWindows_ReturnsUnixPermissionManager(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );

            % Act
            mgr = mcpserver.internal.fs.internal.permissionmanager.createPermissionManager( ...
                OSFacade=mockOS ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                mgr, ...
                ?mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager, ...
                "Factory must return UnixPermissionManager when ispc()=false" ...
            );
        end

        function testCreatePermissionManager_OnWindows_ReturnsWindowsPermissionManager(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(true) ...
            );

            % Act
            mgr = mcpserver.internal.fs.internal.permissionmanager.createPermissionManager( ...
                OSFacade=mockOS ...
            );

            % Assert
            testCase.verifyInstanceOf( ...
                mgr, ...
                ?mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager, ...
                "Factory must return WindowsPermissionManager when ispc()=true" ...
            );
        end

        function testCreatePermissionManager_NoArgs_ReturnsAPermissionManager(testCase)
            % Covers the no-args call path used by DefaultFSAdaptor's
            % property default. Exercises the DefaultOSFacade default
            % expression in the factory's arguments block, so the result
            % depends on the actual platform; the assertion is therefore
            % only on the abstract type.

            % Act
            mgr = mcpserver.internal.fs.internal.permissionmanager.createPermissionManager();

            % Assert
            testCase.verifyInstanceOf( ...
                mgr, ...
                ?mcpserver.internal.fs.internal.permissionmanager.PermissionManager, ...
                "Factory with no args must return a PermissionManager" ...
            );
        end

        function testCreatePermissionManager_OnNonWindows_ResultClassDoesNotLiveInWindowsAclOrDotnetPackage(testCase)
            % The result class itself must not live under +windowsacl or
            % +dotnet. Guards against future regressions where a sibling
            % Windows-only class is wired into the non-Windows branch.

            % Arrange
            import matlab.mock.actions.AssignOutputs
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );
            when( ...
                osBehavior.ispc().withExactInputs(), ...
                AssignOutputs(false) ...
            );

            % Act
            mgr = mcpserver.internal.fs.internal.permissionmanager.createPermissionManager( ...
                OSFacade=mockOS ...
            );

            % Assert
            mc = metaclass(mgr);
            className = string(mc.Name);
            testCase.verifyFalse( ...
                contains(className, ".windowsacl.") || contains(className, ".dotnet."), ...
                sprintf( ...
                    "Class returned by the factory on non-Windows must not live under +windowsacl or +dotnet, got: %s", ...
                    className ...
                ) ...
            );
        end
    end

end
