classdef UnixPermissionManagerTest < matlab.mock.TestCase
    %UnixPermissionManagerTest Tests for UnixPermissionManager (Linux and macOS).
    %   Verifies that UnixPermissionManager correctly manages file and
    %   folder permissions via chmod.

    % Copyright 2026 The MathWorks, Inc.

    methods (Test)
        function testUnixPermissionManager_SetPermissionsToUserOnly_HappyPath_Unix_Folder(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", ".MathWorks", "MATLABMCPServer");
            attribs = struct("directory", true);
            expectedChmodCmd = sprintf("chmod 700 '%s'", expectedPath);

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(true, attribs, '') ...
            );
            when( ...
                osBehavior.system(expectedChmodCmd), ...
                AssignOutputs(0, '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            % Act
            fs.setPermissionsToUserOnly(expectedPath);

            % Assert
            testCase.verifyCalled( ...
                osBehavior.system(expectedChmodCmd), ...
                "Should call chmod with 700 for folders" ...
            );
        end

        function testUnixPermissionManager_SetPermissionsToUserOnly_HappyPath_Unix_File(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", "file.txt");
            attribs = struct("directory", false);
            expectedChmodCmd = sprintf("chmod 600 '%s'", expectedPath);

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(true, attribs, '') ...
            );
            when( ...
                osBehavior.system(expectedChmodCmd), ...
                AssignOutputs(0, '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            % Act
            fs.setPermissionsToUserOnly(expectedPath);

            % Assert
            testCase.verifyCalled( ...
                osBehavior.system(expectedChmodCmd), ...
                "Should call chmod with 600 for files" ...
            );
        end

        function testUnixPermissionManager_SetPermissionsToUserOnly_Unix_PathWithSingleQuote(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", "it's a folder");
            escapedPath = fullfile("home", "user", "it'\''s a folder");
            attribs = struct("directory", true);
            expectedChmodCmd = sprintf("chmod 700 '%s'", escapedPath);

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(true, attribs, '') ...
            );
            when( ...
                osBehavior.system(expectedChmodCmd), ...
                AssignOutputs(0, '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            % Act
            fs.setPermissionsToUserOnly(expectedPath);

            % Assert
            testCase.verifyCalled( ...
                osBehavior.system(expectedChmodCmd), ...
                "Should escape single quotes in path for shell safety" ...
            );
        end

        function testUnixPermissionManager_SetPermissionsToUserOnly_Unix_ChmodFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, osBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", ".MathWorks", "MATLABMCPServer");
            attribs = struct("directory", true);
            expectedChmodCmd = sprintf("chmod 700 '%s'", expectedPath);

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(true, attribs, '') ...
            );
            when( ...
                osBehavior.system(expectedChmodCmd), ...
                AssignOutputs(1, 'Operation not permitted') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            expectedError = mcpserver.internal.error.Errors.FailedToSetPermissions( ...
                expectedPath ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() fs.setPermissionsToUserOnly(expectedPath), ...
                expectedError.identifier, ...
                "Should throw FailedToSetPermissions when chmod fails" ...
            );
        end

        function testUnixPermissionManager_SetPermissionsToUserOnly_Unix_GetAttribsFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", ".MathWorks", "MATLABMCPServer");

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(false, '', '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            expectedError = mcpserver.internal.error.Errors.FailedToGetFileAttributes( ...
                expectedPath ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() fs.setPermissionsToUserOnly(expectedPath), ...
                expectedError.identifier, ...
                "Should throw FailedToGetFileAttributes when fileattrib fails" ...
            );
        end

        function testUnixPermissionManager_CheckPermissionsIsUserOnly_HappyPath_Unix_(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", ".MathWorks", "MATLABMCPServer");
            attribs = struct( ...
                "directory", true, ...
                "UserRead", true, ...
                "UserWrite", true, ...
                "UserExecute", true, ...
                "GroupRead", false, ...
                "GroupWrite", false, ...
                "GroupExecute", false, ...
                "OtherRead", false, ...
                "OtherWrite", false, ...
                "OtherExecute", false ...
            );

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(true, attribs, '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyTrue(result, ...
                "Should return true when only user has access");
        end

        function testUnixPermissionManager_CheckPermissionsIsUserOnly_Unix_GroupHasAccess(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", ".MathWorks", "MATLABMCPServer");
            attribs = struct( ...
                "directory", true, ...
                "UserRead", true, ...
                "UserWrite", true, ...
                "UserExecute", true, ...
                "GroupRead", true, ...
                "GroupWrite", false, ...
                "GroupExecute", false, ...
                "OtherRead", false, ...
                "OtherWrite", false, ...
                "OtherExecute", false ...
            );

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(true, attribs, '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when group has read access");
        end

        function testUnixPermissionManager_CheckPermissionsIsUserOnly_Unix_OtherHasAccess(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", ".MathWorks", "MATLABMCPServer");
            attribs = struct( ...
                "directory", true, ...
                "UserRead", true, ...
                "UserWrite", true, ...
                "UserExecute", true, ...
                "GroupRead", false, ...
                "GroupWrite", false, ...
                "GroupExecute", false, ...
                "OtherRead", false, ...
                "OtherWrite", true, ...
                "OtherExecute", false ...
            );

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(true, attribs, '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when other has write access");
        end

        function testUnixPermissionManager_CheckPermissionsIsUserOnly_HappyPath_Unix_File(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", "file.json");
            attribs = struct( ...
                "directory", false, ...
                "UserRead", true, ...
                "UserWrite", true, ...
                "UserExecute", false, ...
                "GroupRead", false, ...
                "GroupWrite", false, ...
                "GroupExecute", false, ...
                "OtherRead", false, ...
                "OtherWrite", false, ...
                "OtherExecute", false ...
            );

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(true, attribs, '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyTrue(result, ...
                "Should return true for file with 600 permissions (rw-------)");
        end

        function testUnixPermissionManager_CheckPermissionsIsUserOnly_Unix_File_HasExecute(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", "file.json");
            attribs = struct( ...
                "directory", false, ...
                "UserRead", true, ...
                "UserWrite", true, ...
                "UserExecute", true, ...
                "GroupRead", false, ...
                "GroupWrite", false, ...
                "GroupExecute", false, ...
                "OtherRead", false, ...
                "OtherWrite", false, ...
                "OtherExecute", false ...
            );

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(true, attribs, '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false for file with execute bit set (700 instead of 600)");
        end

        function testUnixPermissionManager_CheckPermissionsIsUserOnly_Unix_FileattribFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockOS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.os.OSFacade, ...
                Strict=true ...
            );

            expectedPath = fullfile("home", "user", ".MathWorks", "MATLABMCPServer");

            when( ...
                fsBehavior.fileattrib(expectedPath), ...
                AssignOutputs(false, '', '') ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.UnixPermissionManager( ...
                FSFacade=mockFS, ...
                OSFacade=mockOS ...
            );

            expectedError = mcpserver.internal.error.Errors.FailedToGetFileAttributes( ...
                expectedPath ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() fs.checkPermissionsIsUserOnly(expectedPath), ...
                expectedError.identifier, ...
                "Should throw FailedToGetFileAttributes when fileattrib fails" ...
            );
        end
    end

end
