classdef WindowsPermissionManagerTest < matlab.mock.TestCase
    %WindowsPermissionManagerTest Tests for WindowsPermissionManager.
    %   Verifies that WindowsPermissionManager correctly manages file and
    %   folder permissions via Windows ACLs.

    % Copyright 2026 The MathWorks, Inc.

    properties (Constant, Access = private)
        % Well-known SIDs (must match WindowsPermissionManager constants)
        SYSTEM_SID = "S-1-5-18"
        ADMINISTRATORS_SID = "S-1-5-32-544"
    end

    methods (Test)
        function testWindowsPermissionManager_SetPermissionsToUserOnly_HappyPath_Windows_Folder(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            expectedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                fsBehavior.isfolder(expectedPath), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.setProtectedACL(expectedPath, expectedSids, true), ...
                DoNothing ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            fs.setPermissionsToUserOnly(expectedPath);

            % Assert
            testCase.verifyCalled( ...
                securityBehavior.setProtectedACL(expectedPath, expectedSids, true), ...
                "Should call setProtectedACL with user, SYSTEM, and Administrators SIDs for directory" ...
            );
        end

        function testWindowsPermissionManager_SetPermissionsToUserOnly_HappyPath_Windows_File(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "file.json");
            expectedUserSid = "S-1-5-21-12345";
            expectedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                fsBehavior.isfolder(expectedPath), ...
                AssignOutputs(false) ...
            );
            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.setProtectedACL(expectedPath, expectedSids, false), ...
                DoNothing ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            fs.setPermissionsToUserOnly(expectedPath);

            % Assert
            testCase.verifyCalled( ...
                securityBehavior.setProtectedACL(expectedPath, expectedSids, false), ...
                "Should call setProtectedACL with user, SYSTEM, and Administrators SIDs for file" ...
            );
        end

        function testWindowsPermissionManager_SetPermissionsToUserOnly_Windows_SetACLFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.ThrowException

            [mockFS, fsBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            expectedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                fsBehavior.isfolder(expectedPath), ...
                AssignOutputs(true) ...
            );
            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.setProtectedACL(expectedPath, expectedSids, true), ...
                ThrowException(MException("test:error", "Access denied")) ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            expectedError = mcpserver.internal.error.Errors.FailedToSetPermissions( ...
                expectedPath ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() fs.setPermissionsToUserOnly(expectedPath), ...
                expectedError.identifier, ...
                "Should throw FailedToSetPermissions when setProtectedACL fails" ...
            );
        end

        function testWindowsPermissionManager_CheckPermissionsIsUserOnly_HappyPath_Windows(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSIDs(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDACLProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyTrue(result, ...
                "Should return true when only user, SYSTEM, and Administrators have access");
        end

        function testWindowsPermissionManager_CheckPermissionsIsUserOnly_Windows_UnexpectedAce(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            unexpectedSid = "S-1-5-21-99999";
            returnedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID, unexpectedSid];

            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSIDs(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDACLProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when an unexpected SID has access");
        end

        function testWindowsPermissionManager_CheckPermissionsIsUserOnly_Windows_UserMissing(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSIDs(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDACLProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when current user SID is not in the ACL");
        end

        function testWindowsPermissionManager_CheckPermissionsIsUserOnly_Windows_SystemMissing(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [expectedUserSid, testCase.ADMINISTRATORS_SID];

            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSIDs(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDACLProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when SYSTEM SID is missing from the ACL");
        end

        function testWindowsPermissionManager_CheckPermissionsIsUserOnly_Windows_AdministratorsMissing(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [expectedUserSid, testCase.SYSTEM_SID];

            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSIDs(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDACLProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when Administrators SID is missing from the ACL");
        end

        function testWindowsPermissionManager_CheckPermissionsIsUserOnly_Windows_DACLNotProtected(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = [expectedUserSid, testCase.SYSTEM_SID, testCase.ADMINISTRATORS_SID];

            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSIDs(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDACLProtected(expectedPath), ...
                AssignOutputs(false) ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when DACL is not protected (inheritance not blocked)");
        end

        function testWindowsPermissionManager_CheckPermissionsIsUserOnly_Windows_EmptyACL(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs

            [mockFS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");
            expectedUserSid = "S-1-5-21-12345";
            returnedSids = string.empty;

            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                AssignOutputs(expectedUserSid) ...
            );
            when( ...
                securityBehavior.getAllowedSIDs(expectedPath), ...
                AssignOutputs(returnedSids) ...
            );
            when( ...
                securityBehavior.isDACLProtected(expectedPath), ...
                AssignOutputs(true) ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            % Act
            result = fs.checkPermissionsIsUserOnly(expectedPath);

            % Assert
            testCase.verifyFalse(result, ...
                "Should return false when ACL has no entries");
        end

        function testWindowsPermissionManager_CheckPermissionsIsUserOnly_Windows_GetACLFails(testCase)
            % Arrange
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.ThrowException

            [mockFS, ~] = testCase.createMock( ...
                ?mcpserver.internal.facade.fs.FSFacade, ...
                Strict=true ...
            );
            [mockSecurity, securityBehavior] = testCase.createMock( ...
                ?mcpserver.internal.fs.internal.permissionmanager.internal.windowsacl.WindowsACLManager, ...
                Strict=true ...
            );

            expectedPath = fullfile("C:", "Users", "user", "AppData");

            when( ...
                securityBehavior.getCurrentUserSID().withExactInputs(), ...
                ThrowException(MException("test:error", "Access denied")) ...
            );

            fs = mcpserver.internal.fs.internal.permissionmanager.WindowsPermissionManager( ...
                FSFacade=mockFS, ...
                WindowsACLManager=mockSecurity ...
            );

            expectedError = mcpserver.internal.error.Errors.FailedToGetFileAttributes( ...
                expectedPath ...
            );

            % Act & Assert
            testCase.verifyError( ...
                @() fs.checkPermissionsIsUserOnly(expectedPath), ...
                expectedError.identifier, ...
                "Should throw FailedToGetFileAttributes when security facade fails" ...
            );
        end
    end

end
