// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// HandleProcessToKill provides a mock function for the type MockHandler
func (_mock *MockHandler) HandleProcessToKill(req messages.ProcessToKillRequest) (messages.ProcessToKillResponse, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for HandleProcessToKill")
	}

	var r0 messages.ProcessToKillResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(messages.ProcessToKillRequest) (messages.ProcessToKillResponse, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(messages.ProcessToKillRequest) messages.ProcessToKillResponse); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(messages.ProcessToKillResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(messages.ProcessToKillRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_HandleProcessToKill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleProcessToKill'
type MockHandler_HandleProcessToKill_Call struct {
	*mock.Call
}

// HandleProcessToKill is a helper method to define mock.On call
//   - req messages.ProcessToKillRequest
func (_e *MockHandler_Expecter) HandleProcessToKill(req interface{}) *MockHandler_HandleProcessToKill_Call {
	return &MockHandler_HandleProcessToKill_Call{Call: _e.mock.On("HandleProcessToKill", req)}
}

func (_c *MockHandler_HandleProcessToKill_Call) Run(run func(req messages.ProcessToKillRequest)) *MockHandler_HandleProcessToKill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 messages.ProcessToKillRequest
		if args[0] != nil {
			arg0 = args[0].(messages.ProcessToKillRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_HandleProcessToKill_Call) Return(processToKillResponse messages.ProcessToKillResponse, err error) *MockHandler_HandleProcessToKill_Call {
	_c.Call.Return(processToKillResponse, err)
	return _c
}

func (_c *MockHandler_HandleProcessToKill_Call) RunAndReturn(run func(req messages.ProcessToKillRequest) (messages.ProcessToKillResponse, error)) *MockHandler_HandleProcessToKill_Call {
	_c.Call.Return(run)
	return _c
}

// HandleShutdown provides a mock function for the type MockHandler
func (_mock *MockHandler) HandleShutdown(req messages.ShutdownRequest) (messages.ShutdownResponse, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for HandleShutdown")
	}

	var r0 messages.ShutdownResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(messages.ShutdownRequest) (messages.ShutdownResponse, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(messages.ShutdownRequest) messages.ShutdownResponse); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(messages.ShutdownResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(messages.ShutdownRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandler_HandleShutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleShutdown'
type MockHandler_HandleShutdown_Call struct {
	*mock.Call
}

// HandleShutdown is a helper method to define mock.On call
//   - req messages.ShutdownRequest
func (_e *MockHandler_Expecter) HandleShutdown(req interface{}) *MockHandler_HandleShutdown_Call {
	return &MockHandler_HandleShutdown_Call{Call: _e.mock.On("HandleShutdown", req)}
}

func (_c *MockHandler_HandleShutdown_Call) Run(run func(req messages.ShutdownRequest)) *MockHandler_HandleShutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 messages.ShutdownRequest
		if args[0] != nil {
			arg0 = args[0].(messages.ShutdownRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_HandleShutdown_Call) Return(shutdownResponse messages.ShutdownResponse, err error) *MockHandler_HandleShutdown_Call {
	_c.Call.Return(shutdownResponse, err)
	return _c
}

func (_c *MockHandler_HandleShutdown_Call) RunAndReturn(run func(req messages.ShutdownRequest) (messages.ShutdownResponse, error)) *MockHandler_HandleShutdown_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterShutdownFunction provides a mock function for the type MockHandler
func (_mock *MockHandler) RegisterShutdownFunction(fn func()) {
	_mock.Called(fn)
	return
}

// MockHandler_RegisterShutdownFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterShutdownFunction'
type MockHandler_RegisterShutdownFunction_Call struct {
	*mock.Call
}

// RegisterShutdownFunction is a helper method to define mock.On call
//   - fn func()
func (_e *MockHandler_Expecter) RegisterShutdownFunction(fn interface{}) *MockHandler_RegisterShutdownFunction_Call {
	return &MockHandler_RegisterShutdownFunction_Call{Call: _e.mock.On("RegisterShutdownFunction", fn)}
}

func (_c *MockHandler_RegisterShutdownFunction_Call) Run(run func(fn func())) *MockHandler_RegisterShutdownFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_RegisterShutdownFunction_Call) Return() *MockHandler_RegisterShutdownFunction_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_RegisterShutdownFunction_Call) RunAndReturn(run func(fn func())) *MockHandler_RegisterShutdownFunction_Call {
	_c.Run(run)
	return _c
}

// TerminateAllProcesses provides a mock function for the type MockHandler
func (_mock *MockHandler) TerminateAllProcesses() {
	_mock.Called()
	return
}

// MockHandler_TerminateAllProcesses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TerminateAllProcesses'
type MockHandler_TerminateAllProcesses_Call struct {
	*mock.Call
}

// TerminateAllProcesses is a helper method to define mock.On call
func (_e *MockHandler_Expecter) TerminateAllProcesses() *MockHandler_TerminateAllProcesses_Call {
	return &MockHandler_TerminateAllProcesses_Call{Call: _e.mock.On("TerminateAllProcesses")}
}

func (_c *MockHandler_TerminateAllProcesses_Call) Run(run func()) *MockHandler_TerminateAllProcesses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_TerminateAllProcesses_Call) Return() *MockHandler_TerminateAllProcesses_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_TerminateAllProcesses_Call) RunAndReturn(run func()) *MockHandler_TerminateAllProcesses_Call {
	_c.Run(run)
	return _c
}
