// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessHandler creates a new instance of MockProcessHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessHandler {
	mock := &MockProcessHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessHandler is an autogenerated mock type for the ProcessHandler type
type MockProcessHandler struct {
	mock.Mock
}

type MockProcessHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessHandler) EXPECT() *MockProcessHandler_Expecter {
	return &MockProcessHandler_Expecter{mock: &_m.Mock}
}

// KillProcess provides a mock function for the type MockProcessHandler
func (_mock *MockProcessHandler) KillProcess(processPid int) error {
	ret := _mock.Called(processPid)

	if len(ret) == 0 {
		panic("no return value specified for KillProcess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(processPid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcessHandler_KillProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillProcess'
type MockProcessHandler_KillProcess_Call struct {
	*mock.Call
}

// KillProcess is a helper method to define mock.On call
//   - processPid int
func (_e *MockProcessHandler_Expecter) KillProcess(processPid interface{}) *MockProcessHandler_KillProcess_Call {
	return &MockProcessHandler_KillProcess_Call{Call: _e.mock.On("KillProcess", processPid)}
}

func (_c *MockProcessHandler_KillProcess_Call) Run(run func(processPid int)) *MockProcessHandler_KillProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcessHandler_KillProcess_Call) Return(err error) *MockProcessHandler_KillProcess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcessHandler_KillProcess_Call) RunAndReturn(run func(processPid int) error) *MockProcessHandler_KillProcess_Call {
	_c.Call.Return(run)
	return _c
}
