// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDirectory creates a new instance of MockDirectory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDirectory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDirectory {
	mock := &MockDirectory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDirectory is an autogenerated mock type for the Directory type
type MockDirectory struct {
	mock.Mock
}

type MockDirectory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDirectory) EXPECT() *MockDirectory_Expecter {
	return &MockDirectory_Expecter{mock: &_m.Mock}
}

// BaseDir provides a mock function for the type MockDirectory
func (_mock *MockDirectory) BaseDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDirectory_BaseDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseDir'
type MockDirectory_BaseDir_Call struct {
	*mock.Call
}

// BaseDir is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) BaseDir() *MockDirectory_BaseDir_Call {
	return &MockDirectory_BaseDir_Call{Call: _e.mock.On("BaseDir")}
}

func (_c *MockDirectory_BaseDir_Call) Run(run func()) *MockDirectory_BaseDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_BaseDir_Call) Return(s string) *MockDirectory_BaseDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDirectory_BaseDir_Call) RunAndReturn(run func() string) *MockDirectory_BaseDir_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubDir provides a mock function for the type MockDirectory
func (_mock *MockDirectory) CreateSubDir(pattern string) (string, messages.Error) {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubDir")
	}

	var r0 string
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func(string) (string, messages.Error)); ok {
		return returnFunc(pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(pattern)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) messages.Error); ok {
		r1 = returnFunc(pattern)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockDirectory_CreateSubDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubDir'
type MockDirectory_CreateSubDir_Call struct {
	*mock.Call
}

// CreateSubDir is a helper method to define mock.On call
//   - pattern string
func (_e *MockDirectory_Expecter) CreateSubDir(pattern interface{}) *MockDirectory_CreateSubDir_Call {
	return &MockDirectory_CreateSubDir_Call{Call: _e.mock.On("CreateSubDir", pattern)}
}

func (_c *MockDirectory_CreateSubDir_Call) Run(run func(pattern string)) *MockDirectory_CreateSubDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDirectory_CreateSubDir_Call) Return(s string, error messages.Error) *MockDirectory_CreateSubDir_Call {
	_c.Call.Return(s, error)
	return _c
}

func (_c *MockDirectory_CreateSubDir_Call) RunAndReturn(run func(pattern string) (string, messages.Error)) *MockDirectory_CreateSubDir_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockDirectory
func (_mock *MockDirectory) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDirectory_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockDirectory_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockDirectory_Expecter) ID() *MockDirectory_ID_Call {
	return &MockDirectory_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockDirectory_ID_Call) Run(run func()) *MockDirectory_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDirectory_ID_Call) Return(s string) *MockDirectory_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDirectory_ID_Call) RunAndReturn(run func() string) *MockDirectory_ID_Call {
	_c.Call.Return(run)
	return _c
}

// RecordToLogger provides a mock function for the type MockDirectory
func (_mock *MockDirectory) RecordToLogger(logger entities.Logger) {
	_mock.Called(logger)
	return
}

// MockDirectory_RecordToLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordToLogger'
type MockDirectory_RecordToLogger_Call struct {
	*mock.Call
}

// RecordToLogger is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockDirectory_Expecter) RecordToLogger(logger interface{}) *MockDirectory_RecordToLogger_Call {
	return &MockDirectory_RecordToLogger_Call{Call: _e.mock.On("RecordToLogger", logger)}
}

func (_c *MockDirectory_RecordToLogger_Call) Run(run func(logger entities.Logger)) *MockDirectory_RecordToLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDirectory_RecordToLogger_Call) Return() *MockDirectory_RecordToLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDirectory_RecordToLogger_Call) RunAndReturn(run func(logger entities.Logger)) *MockDirectory_RecordToLogger_Call {
	_c.Run(run)
	return _c
}
