// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// FindProcess provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) FindProcess(pid int) (osfacade.Process, error) {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for FindProcess")
	}

	var r0 osfacade.Process
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (osfacade.Process, error)); ok {
		return returnFunc(pid)
	}
	if returnFunc, ok := ret.Get(0).(func(int) osfacade.Process); ok {
		r0 = returnFunc(pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.Process)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(pid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSLayer_FindProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindProcess'
type MockOSLayer_FindProcess_Call struct {
	*mock.Call
}

// FindProcess is a helper method to define mock.On call
//   - pid int
func (_e *MockOSLayer_Expecter) FindProcess(pid interface{}) *MockOSLayer_FindProcess_Call {
	return &MockOSLayer_FindProcess_Call{Call: _e.mock.On("FindProcess", pid)}
}

func (_c *MockOSLayer_FindProcess_Call) Run(run func(pid int)) *MockOSLayer_FindProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_FindProcess_Call) Return(process osfacade.Process, err error) *MockOSLayer_FindProcess_Call {
	_c.Call.Return(process, err)
	return _c
}

func (_c *MockOSLayer_FindProcess_Call) RunAndReturn(run func(pid int) (osfacade.Process, error)) *MockOSLayer_FindProcess_Call {
	_c.Call.Return(run)
	return _c
}

// GOOS provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) GOOS() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GOOS")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOSLayer_GOOS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GOOS'
type MockOSLayer_GOOS_Call struct {
	*mock.Call
}

// GOOS is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) GOOS() *MockOSLayer_GOOS_Call {
	return &MockOSLayer_GOOS_Call{Call: _e.mock.On("GOOS")}
}

func (_c *MockOSLayer_GOOS_Call) Run(run func()) *MockOSLayer_GOOS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_GOOS_Call) Return(s string) *MockOSLayer_GOOS_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOSLayer_GOOS_Call) RunAndReturn(run func() string) *MockOSLayer_GOOS_Call {
	_c.Call.Return(run)
	return _c
}
