// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/config"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/application/definition"
	tools0 "github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/mcp/tools/basetool"
	"github.com/matlab/matlab-mcp-server/internal/adaptors/sdk/tools"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConvertibleTool creates a new instance of MockConvertibleTool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConvertibleTool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConvertibleTool {
	mock := &MockConvertibleTool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConvertibleTool is an autogenerated mock type for the ConvertibleTool type
type MockConvertibleTool struct {
	mock.Mock
}

type MockConvertibleTool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConvertibleTool) EXPECT() *MockConvertibleTool_Expecter {
	return &MockConvertibleTool_Expecter{mock: &_m.Mock}
}

// ToInternal provides a mock function for the type MockConvertibleTool
func (_mock *MockConvertibleTool) ToInternal(toolCallRequestFactory tools.ToolCallRequestFactory, loggerFactory basetool.LoggerFactory, telemetryFactory basetool.TelemetryFactory, config1 config.GenericConfig, messageCatalog definition.MessageCatalog) tools0.Tool {
	ret := _mock.Called(toolCallRequestFactory, loggerFactory, telemetryFactory, config1, messageCatalog)

	if len(ret) == 0 {
		panic("no return value specified for ToInternal")
	}

	var r0 tools0.Tool
	if returnFunc, ok := ret.Get(0).(func(tools.ToolCallRequestFactory, basetool.LoggerFactory, basetool.TelemetryFactory, config.GenericConfig, definition.MessageCatalog) tools0.Tool); ok {
		r0 = returnFunc(toolCallRequestFactory, loggerFactory, telemetryFactory, config1, messageCatalog)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tools0.Tool)
		}
	}
	return r0
}

// MockConvertibleTool_ToInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToInternal'
type MockConvertibleTool_ToInternal_Call struct {
	*mock.Call
}

// ToInternal is a helper method to define mock.On call
//   - toolCallRequestFactory tools.ToolCallRequestFactory
//   - loggerFactory basetool.LoggerFactory
//   - telemetryFactory basetool.TelemetryFactory
//   - config1 config.GenericConfig
//   - messageCatalog definition.MessageCatalog
func (_e *MockConvertibleTool_Expecter) ToInternal(toolCallRequestFactory interface{}, loggerFactory interface{}, telemetryFactory interface{}, config1 interface{}, messageCatalog interface{}) *MockConvertibleTool_ToInternal_Call {
	return &MockConvertibleTool_ToInternal_Call{Call: _e.mock.On("ToInternal", toolCallRequestFactory, loggerFactory, telemetryFactory, config1, messageCatalog)}
}

func (_c *MockConvertibleTool_ToInternal_Call) Run(run func(toolCallRequestFactory tools.ToolCallRequestFactory, loggerFactory basetool.LoggerFactory, telemetryFactory basetool.TelemetryFactory, config1 config.GenericConfig, messageCatalog definition.MessageCatalog)) *MockConvertibleTool_ToInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tools.ToolCallRequestFactory
		if args[0] != nil {
			arg0 = args[0].(tools.ToolCallRequestFactory)
		}
		var arg1 basetool.LoggerFactory
		if args[1] != nil {
			arg1 = args[1].(basetool.LoggerFactory)
		}
		var arg2 basetool.TelemetryFactory
		if args[2] != nil {
			arg2 = args[2].(basetool.TelemetryFactory)
		}
		var arg3 config.GenericConfig
		if args[3] != nil {
			arg3 = args[3].(config.GenericConfig)
		}
		var arg4 definition.MessageCatalog
		if args[4] != nil {
			arg4 = args[4].(definition.MessageCatalog)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockConvertibleTool_ToInternal_Call) Return(tool tools0.Tool) *MockConvertibleTool_ToInternal_Call {
	_c.Call.Return(tool)
	return _c
}

func (_c *MockConvertibleTool_ToInternal_Call) RunAndReturn(run func(toolCallRequestFactory tools.ToolCallRequestFactory, loggerFactory basetool.LoggerFactory, telemetryFactory basetool.TelemetryFactory, config1 config.GenericConfig, messageCatalog definition.MessageCatalog) tools0.Tool) *MockConvertibleTool_ToInternal_Call {
	_c.Call.Return(run)
	return _c
}

// mwToolSeal provides a mock function for the type MockConvertibleTool
func (_mock *MockConvertibleTool) mwToolSeal() {
	_mock.Called()
	return
}

// MockConvertibleTool_mwToolSeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mwToolSeal'
type MockConvertibleTool_mwToolSeal_Call struct {
	*mock.Call
}

// mwToolSeal is a helper method to define mock.On call
func (_e *MockConvertibleTool_Expecter) mwToolSeal() *MockConvertibleTool_mwToolSeal_Call {
	return &MockConvertibleTool_mwToolSeal_Call{Call: _e.mock.On("mwToolSeal")}
}

func (_c *MockConvertibleTool_mwToolSeal_Call) Run(run func()) *MockConvertibleTool_mwToolSeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConvertibleTool_mwToolSeal_Call) Return() *MockConvertibleTool_mwToolSeal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConvertibleTool_mwToolSeal_Call) RunAndReturn(run func()) *MockConvertibleTool_mwToolSeal_Call {
	_c.Run(run)
	return _c
}
