// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoggerFactory creates a new instance of MockLoggerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerFactory {
	mock := &MockLoggerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggerFactory is an autogenerated mock type for the LoggerFactory type
type MockLoggerFactory struct {
	mock.Mock
}

type MockLoggerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerFactory) EXPECT() *MockLoggerFactory_Expecter {
	return &MockLoggerFactory_Expecter{mock: &_m.Mock}
}

// NewMCPSessionLogger provides a mock function for the type MockLoggerFactory
func (_mock *MockLoggerFactory) NewMCPSessionLogger(session *mcp.ServerSession) (entities.Logger, messages.Error) {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for NewMCPSessionLogger")
	}

	var r0 entities.Logger
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func(*mcp.ServerSession) (entities.Logger, messages.Error)); ok {
		return returnFunc(session)
	}
	if returnFunc, ok := ret.Get(0).(func(*mcp.ServerSession) entities.Logger); ok {
		r0 = returnFunc(session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.Logger)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*mcp.ServerSession) messages.Error); ok {
		r1 = returnFunc(session)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockLoggerFactory_NewMCPSessionLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewMCPSessionLogger'
type MockLoggerFactory_NewMCPSessionLogger_Call struct {
	*mock.Call
}

// NewMCPSessionLogger is a helper method to define mock.On call
//   - session *mcp.ServerSession
func (_e *MockLoggerFactory_Expecter) NewMCPSessionLogger(session interface{}) *MockLoggerFactory_NewMCPSessionLogger_Call {
	return &MockLoggerFactory_NewMCPSessionLogger_Call{Call: _e.mock.On("NewMCPSessionLogger", session)}
}

func (_c *MockLoggerFactory_NewMCPSessionLogger_Call) Run(run func(session *mcp.ServerSession)) *MockLoggerFactory_NewMCPSessionLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mcp.ServerSession
		if args[0] != nil {
			arg0 = args[0].(*mcp.ServerSession)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoggerFactory_NewMCPSessionLogger_Call) Return(logger entities.Logger, error messages.Error) *MockLoggerFactory_NewMCPSessionLogger_Call {
	_c.Call.Return(logger, error)
	return _c
}

func (_c *MockLoggerFactory_NewMCPSessionLogger_Call) RunAndReturn(run func(session *mcp.ServerSession) (entities.Logger, messages.Error)) *MockLoggerFactory_NewMCPSessionLogger_Call {
	_c.Call.Return(run)
	return _c
}
