// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientInfoStore creates a new instance of MockClientInfoStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInfoStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInfoStore {
	mock := &MockClientInfoStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientInfoStore is an autogenerated mock type for the ClientInfoStore type
type MockClientInfoStore struct {
	mock.Mock
}

type MockClientInfoStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInfoStore) EXPECT() *MockClientInfoStore_Expecter {
	return &MockClientInfoStore_Expecter{mock: &_m.Mock}
}

// SetClientInfo provides a mock function for the type MockClientInfoStore
func (_mock *MockClientInfoStore) SetClientInfo(info entities.MCPClientInfo) {
	_mock.Called(info)
	return
}

// MockClientInfoStore_SetClientInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetClientInfo'
type MockClientInfoStore_SetClientInfo_Call struct {
	*mock.Call
}

// SetClientInfo is a helper method to define mock.On call
//   - info entities.MCPClientInfo
func (_e *MockClientInfoStore_Expecter) SetClientInfo(info interface{}) *MockClientInfoStore_SetClientInfo_Call {
	return &MockClientInfoStore_SetClientInfo_Call{Call: _e.mock.On("SetClientInfo", info)}
}

func (_c *MockClientInfoStore_SetClientInfo_Call) Run(run func(info entities.MCPClientInfo)) *MockClientInfoStore_SetClientInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.MCPClientInfo
		if args[0] != nil {
			arg0 = args[0].(entities.MCPClientInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientInfoStore_SetClientInfo_Call) Return() *MockClientInfoStore_SetClientInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientInfoStore_SetClientInfo_Call) RunAndReturn(run func(info entities.MCPClientInfo)) *MockClientInfoStore_SetClientInfo_Call {
	_c.Run(run)
	return _c
}
