// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDefinition creates a new instance of MockDefinition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDefinition(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDefinition {
	mock := &MockDefinition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDefinition is an autogenerated mock type for the Definition type
type MockDefinition struct {
	mock.Mock
}

type MockDefinition_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDefinition) EXPECT() *MockDefinition_Expecter {
	return &MockDefinition_Expecter{mock: &_m.Mock}
}

// Instructions provides a mock function for the type MockDefinition
func (_mock *MockDefinition) Instructions() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Instructions")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDefinition_Instructions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instructions'
type MockDefinition_Instructions_Call struct {
	*mock.Call
}

// Instructions is a helper method to define mock.On call
func (_e *MockDefinition_Expecter) Instructions() *MockDefinition_Instructions_Call {
	return &MockDefinition_Instructions_Call{Call: _e.mock.On("Instructions")}
}

func (_c *MockDefinition_Instructions_Call) Run(run func()) *MockDefinition_Instructions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDefinition_Instructions_Call) Return(s string) *MockDefinition_Instructions_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDefinition_Instructions_Call) RunAndReturn(run func() string) *MockDefinition_Instructions_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockDefinition
func (_mock *MockDefinition) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDefinition_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDefinition_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDefinition_Expecter) Name() *MockDefinition_Name_Call {
	return &MockDefinition_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDefinition_Name_Call) Run(run func()) *MockDefinition_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDefinition_Name_Call) Return(s string) *MockDefinition_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDefinition_Name_Call) RunAndReturn(run func() string) *MockDefinition_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Title provides a mock function for the type MockDefinition
func (_mock *MockDefinition) Title() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Title")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDefinition_Title_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Title'
type MockDefinition_Title_Call struct {
	*mock.Call
}

// Title is a helper method to define mock.On call
func (_e *MockDefinition_Expecter) Title() *MockDefinition_Title_Call {
	return &MockDefinition_Title_Call{Call: _e.mock.On("Title")}
}

func (_c *MockDefinition_Title_Call) Run(run func()) *MockDefinition_Title_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDefinition_Title_Call) Return(s string) *MockDefinition_Title_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDefinition_Title_Call) RunAndReturn(run func() string) *MockDefinition_Title_Call {
	_c.Call.Return(run)
	return _c
}
