// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/server/handler"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandlerFactory creates a new instance of MockHandlerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandlerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandlerFactory {
	mock := &MockHandlerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandlerFactory is an autogenerated mock type for the HandlerFactory type
type MockHandlerFactory struct {
	mock.Mock
}

type MockHandlerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandlerFactory) EXPECT() *MockHandlerFactory_Expecter {
	return &MockHandlerFactory_Expecter{mock: &_m.Mock}
}

// Handler provides a mock function for the type MockHandlerFactory
func (_mock *MockHandlerFactory) Handler() (handler.Handler, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 handler.Handler
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (handler.Handler, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() handler.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(handler.Handler)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHandlerFactory_Handler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handler'
type MockHandlerFactory_Handler_Call struct {
	*mock.Call
}

// Handler is a helper method to define mock.On call
func (_e *MockHandlerFactory_Expecter) Handler() *MockHandlerFactory_Handler_Call {
	return &MockHandlerFactory_Handler_Call{Call: _e.mock.On("Handler")}
}

func (_c *MockHandlerFactory_Handler_Call) Run(run func()) *MockHandlerFactory_Handler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandlerFactory_Handler_Call) Return(handler1 handler.Handler, err error) *MockHandlerFactory_Handler_Call {
	_c.Call.Return(handler1, err)
	return _c
}

func (_c *MockHandlerFactory_Handler_Call) RunAndReturn(run func() (handler.Handler, error)) *MockHandlerFactory_Handler_Call {
	_c.Call.Return(run)
	return _c
}
