// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/http/server"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHTTPServerFactory creates a new instance of MockHTTPServerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPServerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPServerFactory {
	mock := &MockHTTPServerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPServerFactory is an autogenerated mock type for the HTTPServerFactory type
type MockHTTPServerFactory struct {
	mock.Mock
}

type MockHTTPServerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPServerFactory) EXPECT() *MockHTTPServerFactory_Expecter {
	return &MockHTTPServerFactory_Expecter{mock: &_m.Mock}
}

// NewServerOverUDS provides a mock function for the type MockHTTPServerFactory
func (_mock *MockHTTPServerFactory) NewServerOverUDS(handlers map[string]http.HandlerFunc) (server.HttpServer, error) {
	ret := _mock.Called(handlers)

	if len(ret) == 0 {
		panic("no return value specified for NewServerOverUDS")
	}

	var r0 server.HttpServer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(map[string]http.HandlerFunc) (server.HttpServer, error)); ok {
		return returnFunc(handlers)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]http.HandlerFunc) server.HttpServer); ok {
		r0 = returnFunc(handlers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(server.HttpServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]http.HandlerFunc) error); ok {
		r1 = returnFunc(handlers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPServerFactory_NewServerOverUDS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewServerOverUDS'
type MockHTTPServerFactory_NewServerOverUDS_Call struct {
	*mock.Call
}

// NewServerOverUDS is a helper method to define mock.On call
//   - handlers map[string]http.HandlerFunc
func (_e *MockHTTPServerFactory_Expecter) NewServerOverUDS(handlers interface{}) *MockHTTPServerFactory_NewServerOverUDS_Call {
	return &MockHTTPServerFactory_NewServerOverUDS_Call{Call: _e.mock.On("NewServerOverUDS", handlers)}
}

func (_c *MockHTTPServerFactory_NewServerOverUDS_Call) Run(run func(handlers map[string]http.HandlerFunc)) *MockHTTPServerFactory_NewServerOverUDS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]http.HandlerFunc
		if args[0] != nil {
			arg0 = args[0].(map[string]http.HandlerFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHTTPServerFactory_NewServerOverUDS_Call) Return(httpServer server.HttpServer, err error) *MockHTTPServerFactory_NewServerOverUDS_Call {
	_c.Call.Return(httpServer, err)
	return _c
}

func (_c *MockHTTPServerFactory_NewServerOverUDS_Call) RunAndReturn(run func(handlers map[string]http.HandlerFunc) (server.HttpServer, error)) *MockHTTPServerFactory_NewServerOverUDS_Call {
	_c.Call.Return(run)
	return _c
}
