classdef evaluateWithCaptureTest < matlab.mock.TestCase
    %evaluateWithCaptureTest Tests for mcpserver.internal.evaluateWithCapture

    % Copyright 2026 The MathWorks, Inc.

    methods (Access = private)
        function [mockController, controllerBehavior] = createMockVisibilityController(testCase, showFigureWindows)
            import matlab.mock.actions.DoNothing

            [mockController, controllerBehavior] = testCase.createMock( ...
                ?mcpserver.internal.display.FigureVisibilityController, ...
                Strict=true ...
            );

            if showFigureWindows
                when(controllerBehavior.show().withExactInputs(), DoNothing);
            else
                when(controllerBehavior.hide().withExactInputs(), DoNothing);
            end
            when(controllerBehavior.restore().withExactInputs(), DoNothing);
        end

        function [mockCaptureFacade, captureBehavior] = createMockCaptureFacade(testCase)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockCaptureFacade, captureBehavior] = testCase.createMock( ...
                ?mcpserver.internal.facade.capture.OutputCaptureFacade, ...
                Strict=true ...
            );

            when(captureBehavior.getAllowOutputCapture().withExactInputs(), AssignOutputs(false));
            when(captureBehavior.getSuppressCommandLineOutput().withExactInputs(), AssignOutputs(false));
            when(captureBehavior.getHotlinks().withExactInputs(), AssignOutputs(true));
            when(captureBehavior.pushTextOutputListeners().withExactInputs(), DoNothing);
            when(captureBehavior.resetStructuredFigures().withExactInputs(), DoNothing);
            when(withAnyInputs(captureBehavior.setAllowOutputCapture), DoNothing);
            when(withAnyInputs(captureBehavior.setSuppressCommandLineOutput), DoNothing);
            when(withAnyInputs(captureBehavior.setHotlinks), DoNothing);
            when(captureBehavior.popTextOutputListeners().withExactInputs(), DoNothing);
        end

        function [mockEventSource, eventBehavior] = createMockEventSource(testCase, eventsToReturn)
            import matlab.mock.actions.AssignOutputs

            [mockEventSource, eventBehavior] = testCase.createMock( ...
                ?mcpserver.internal.capture.CapturedEventProvider, ...
                Strict=true ...
            );

            when(eventBehavior.getEvents().withExactInputs(), AssignOutputs(eventsToReturn));
        end

        function [mockDisplayer, displayerBehavior] = createMockEventDisplayer(testCase)
            import matlab.mock.actions.DoNothing

            [mockDisplayer, displayerBehavior] = testCase.createMock( ...
                ?mcpserver.internal.display.console.EventDisplayer, ...
                Strict=true ...
            );

            when(withAnyInputs(displayerBehavior.displayEvents), DoNothing);
        end

        function [mockPoller, pollerBehavior] = createMockEventPoller(testCase, eventsToReturn)
            import matlab.mock.actions.AssignOutputs
            import matlab.mock.actions.DoNothing

            [mockPoller, pollerBehavior] = testCase.createMock( ...
                ?mcpserver.internal.capture.EventPoller, ...
                Strict=true ...
            );

            when(pollerBehavior.start().withExactInputs(), DoNothing);
            when(pollerBehavior.stop().withExactInputs(), DoNothing);
            when(pollerBehavior.flush().withExactInputs(), DoNothing);
            when( ...
                pollerBehavior.getEvents().withExactInputs(), ...
                AssignOutputs(eventsToReturn) ...
            );
        end

        function builder = createPassthroughOutputBuilder(testCase)
            import matlab.mock.actions.Invoke

            [mockConverter, converterBehavior] = testCase.createMock( ...
                ?mcpserver.internal.output.converter.Converter, ...
                Strict=true ...
            );

            when( ...
                withAnyInputs(converterBehavior.convert), ...
                Invoke(@(~, evt) evt) ...
            );

            builder = mcpserver.internal.output.OutputBuilder( ...
                StdoutConverter=mockConverter, ...
                StderrConverter=mockConverter, ...
                VariableDisplayConverter=mockConverter, ...
                WarningConverter=mockConverter, ...
                FigureConverter=mockConverter ...
            );
        end
    end

    methods (Test)
        function testEvaluateWithCapture_HappyPath_FiguresHidden(testCase)
            % Arrange
            [mockController, behavior] = testCase.createMockVisibilityController(false);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "disp('hello')", ...
                ShowFigureWindows=false, ...
                DisplayCapturedEvents=true, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyCalled( ...
                behavior.hide().withExactInputs(), ...
                "hide() should be called when ShowFigureWindows is false" ...
            );
            testCase.verifyCalled( ...
                behavior.restore().withExactInputs(), ...
                "restore() should be called after evaluation" ...
            );
        end

        function testEvaluateWithCapture_HappyPath_FiguresShown(testCase)
            % Arrange
            [mockController, behavior] = testCase.createMockVisibilityController(true);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "disp('hello')", ...
                ShowFigureWindows=true, ...
                DisplayCapturedEvents=true, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyCalled( ...
                behavior.show().withExactInputs(), ...
                "show() should be called when ShowFigureWindows is true" ...
            );
            testCase.verifyNotCalled( ...
                behavior.hide().withExactInputs(), ...
                "hide() should not be called when ShowFigureWindows is true" ...
            );
            testCase.verifyCalled( ...
                behavior.restore().withExactInputs(), ...
                "restore() should be called after evaluation" ...
            );
        end

        function testEvaluateWithCapture_OutputCapture_EnableAndDisable(testCase)
            % Arrange
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockCaptureFacade, captureBehavior] = testCase.createMockCaptureFacade();
            capture = mcpserver.internal.capture.DefaultOutputCapture(Facade=mockCaptureFacade);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayCapturedEvents=true, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                OutputCapture=capture, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyCalled( ...
                captureBehavior.pushTextOutputListeners().withExactInputs(), ...
                "OutputCapture.enable() should call pushTextOutputListeners" ...
            );
            testCase.verifyCalled( ...
                captureBehavior.popTextOutputListeners().withExactInputs(), ...
                "OutputCapture.disable() should call popTextOutputListeners" ...
            );
        end

        function testEvaluateWithCapture_CapturedEventProvider_GetEventsCalled(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockEventSource, eventBehavior] = testCase.createMockEventSource(expectedEvents);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            results = mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayCapturedEvents=true, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                CapturedEventProvider=mockEventSource, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyCalled( ...
                eventBehavior.getEvents().withExactInputs(), ...
                "getEvents() should be called after evaluation" ...
            );
            testCase.verifyLength(results, 1);
            testCase.verifyEqual(results{1}.text, 'hello');
        end

        function testEvaluateWithCapture_UserError_StillDisablesCapture(testCase)
            % Arrange
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockCaptureFacade, captureBehavior] = testCase.createMockCaptureFacade();
            capture = mcpserver.internal.capture.DefaultOutputCapture(Facade=mockCaptureFacade);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            try
                mcpserver.internal.evaluateWithCapture( ...
                    "error('test:e', 'boom')", ...
                    ShowFigureWindows=false, ...
                    DisplayCapturedEvents=true, ...
                    DisplayDuringExecution=false, ...
                    FigureVisibilityController=mockController, ...
                    OutputCapture=capture, ...
                    EventDisplayer=mockDisplayer ...
                );
            catch
            end

            % Assert
            testCase.verifyCalled( ...
                captureBehavior.popTextOutputListeners().withExactInputs(), ...
                "OutputCapture should be disabled even when user code errors" ...
            );
        end

        function testEvaluateWithCapture_UserError_RestoresVisibility(testCase)
            % Arrange
            [mockController, controllerBehavior] = testCase.createMockVisibilityController(false);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            try
                mcpserver.internal.evaluateWithCapture( ...
                    "error('test:e', 'boom')", ...
                    ShowFigureWindows=false, ...
                    DisplayCapturedEvents=true, ...
                    DisplayDuringExecution=false, ...
                    FigureVisibilityController=mockController, ...
                    EventDisplayer=mockDisplayer ...
                );
            catch
            end

            % Assert
            testCase.verifyCalled( ...
                controllerBehavior.restore().withExactInputs(), ...
                "restore() should be called even when user code errors" ...
            );
        end

        function testEvaluateWithCapture_UserError_PreservesOriginalError(testCase)
            % Arrange
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockCaptureFacade, ~] = testCase.createMockCaptureFacade();
            capture = mcpserver.internal.capture.DefaultOutputCapture(Facade=mockCaptureFacade);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act & Assert
            try
                mcpserver.internal.evaluateWithCapture( ...
                    "error('test:e', 'boom')", ...
                    ShowFigureWindows=false, ...
                    DisplayCapturedEvents=true, ...
                    DisplayDuringExecution=false, ...
                    FigureVisibilityController=mockController, ...
                    OutputCapture=capture, ...
                    EventDisplayer=mockDisplayer ...
                );
                testCase.verifyFail("Should have thrown an error");
            catch ME
                testCase.verifySubstring(ME.message, "boom", ...
                    "Error message should contain the original error text" ...
                );
                testCase.verifyEqual(ME.identifier, 'test:e', ...
                    "Error identifier should be preserved" ...
                );
            end
        end

        function testEvaluateWithCapture_UserError_PreservesUserStack(testCase)
            % An error raised by user code from a function should surface
            % its stack frames to the caller, so the LLM can see file/line
            % context. CustomStackException must trim evaluateWithCapture's
            % own frame while preserving the user frames beneath it.

            % Arrange
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockCaptureFacade, ~] = testCase.createMockCaptureFacade();
            capture = mcpserver.internal.capture.DefaultOutputCapture(Facade=mockCaptureFacade);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Define a user function on the path so its frame appears on the stack.
            scratchDir = fullfile(tempdir, "evaluateWithCaptureTest_userStack");
            if ~isfolder(scratchDir)
                mkdir(scratchDir);
            end
            funcPath = fullfile(scratchDir, "userFunc.m");
            fid = fopen(funcPath, 'w');
            fprintf(fid, '%s\n', "function userFunc()", ...
                "    error('user:err', 'inside user function');", "end");
            fclose(fid);
            addpath(scratchDir);
            cleanup = onCleanup(@() cleanupScratch(scratchDir));

            % Act & Assert
            try
                mcpserver.internal.evaluateWithCapture( ...
                    "userFunc()", ...
                    ShowFigureWindows=false, ...
                    DisplayCapturedEvents=true, ...
                    DisplayDuringExecution=false, ...
                    FigureVisibilityController=mockController, ...
                    OutputCapture=capture, ...
                    EventDisplayer=mockDisplayer ...
                );
                testCase.verifyFail("Should have thrown an error");
            catch ME
                testCase.verifyNotEmpty(ME.stack, ...
                    "User function frame should be preserved on the stack");
                testCase.verifyTrue(any({ME.stack.name} == "userFunc"), ...
                    "Stack should contain the user function frame");
                testCase.verifyFalse(any({ME.stack.name} == "evaluateWithCapture"), ...
                    "evaluateWithCapture frame should be trimmed from the user-visible stack");
                testCase.verifyEqual(ME.message, 'inside user function', ...
                    "Message should be the clean original message");
            end
        end

        function testEvaluateWithCapture_UserError_EventsStillCollected(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'partial output'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockEventSource, eventBehavior] = testCase.createMockEventSource(expectedEvents);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            try
                mcpserver.internal.evaluateWithCapture( ...
                    "error('test:e', 'boom')", ...
                    ShowFigureWindows=false, ...
                    DisplayCapturedEvents=true, ...
                    DisplayDuringExecution=false, ...
                    FigureVisibilityController=mockController, ...
                    CapturedEventProvider=mockEventSource, ...
                    EventDisplayer=mockDisplayer ...
                );
            catch
            end

            % Assert
            testCase.verifyCalled( ...
                eventBehavior.getEvents().withExactInputs(), ...
                "getEvents() should still be called even when user code errors" ...
            );
        end

        function testEvaluateWithCapture_DisplayCapturedEventsTrue_CalledWithCollectedEvents(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockEventSource, ~] = testCase.createMockEventSource(expectedEvents);
            [mockDisplayer, displayerBehavior] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayCapturedEvents=true, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                CapturedEventProvider=mockEventSource, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyCalled( ...
                displayerBehavior.displayEvents(expectedEvents), ...
                "displayEvents should be called with the collected events" ...
            );
        end

        function testEvaluateWithCapture_DisplayCapturedEventsFalse_DisplayerNotCalled(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockEventSource, ~] = testCase.createMockEventSource(expectedEvents);
            [mockDisplayer, displayerBehavior] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayCapturedEvents=false, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                CapturedEventProvider=mockEventSource, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyNotCalled( ...
                withAnyInputs(displayerBehavior.displayEvents), ...
                "displayEvents should not be called when DisplayCapturedEvents is false" ...
            );
        end

        function testEvaluateWithCapture_UserError_DisplayEventsCalledBeforeThrow(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'partial output'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockEventSource, ~] = testCase.createMockEventSource(expectedEvents);
            [mockDisplayer, displayerBehavior] = testCase.createMockEventDisplayer();

            % Act
            try
                mcpserver.internal.evaluateWithCapture( ...
                    "error('test:e', 'boom')", ...
                    ShowFigureWindows=false, ...
                    DisplayCapturedEvents=true, ...
                    DisplayDuringExecution=false, ...
                    FigureVisibilityController=mockController, ...
                    CapturedEventProvider=mockEventSource, ...
                    EventDisplayer=mockDisplayer ...
                );
            catch
            end

            % Assert
            testCase.verifyCalled( ...
                displayerBehavior.displayEvents(expectedEvents), ...
                "displayEvents should be called even when user code errors" ...
            );
        end

        function testEvaluateWithCapture_DefaultEventDisplayer_CreatedWhenOmitted(testCase)
            % Arrange
            [mockController, ~] = testCase.createMockVisibilityController(false);

            % Act & Assert
            testCase.verifyWarningFree( ...
                @() mcpserver.internal.evaluateWithCapture( ...
                    "x = 1;", ...
                    ShowFigureWindows=false, ...
                    DisplayDuringExecution=false, ...
                    FigureVisibilityController=mockController ...
                ), ...
                "evaluateWithCapture should work without explicit EventDisplayer");
        end

        function testEvaluateWithCapture_WithEventPoller_StartsAndStopsPoller(testCase)
            % Arrange
            events = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockPoller, pollerBehavior] = testCase.createMockEventPoller(events);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                EventPoller=mockPoller, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyCalled( ...
                pollerBehavior.start().withExactInputs(), ...
                "start() should be called before evaluation" ...
            );
            testCase.verifyCalled( ...
                pollerBehavior.stop().withExactInputs(), ...
                "stop() should be called after evaluation" ...
            );
            testCase.verifyCalled( ...
                pollerBehavior.flush().withExactInputs(), ...
                "flush() should be called after stop for final events" ...
            );
        end

        function testEvaluateWithCapture_WithEventPoller_UsesPollerAsEventSource(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockPoller, pollerBehavior] = testCase.createMockEventPoller(expectedEvents);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();
            builder = testCase.createPassthroughOutputBuilder();

            % Act
            results = mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                EventPoller=mockPoller, ...
                EventDisplayer=mockDisplayer, ...
                OutputBuilder=builder ...
            );

            % Assert
            testCase.verifyCalled( ...
                pollerBehavior.getEvents().withExactInputs(), ...
                "getEvents() should be called on the poller" ...
            );
            testCase.verifyEqual(results, {expectedEvents}, ...
                "Return value should come from the poller's getEvents()" ...
            );
        end

        function testEvaluateWithCapture_WithEventPoller_SkipsPostHocDisplay(testCase)
            % Arrange
            events = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockPoller, ~] = testCase.createMockEventPoller(events);
            [mockDisplayer, displayerBehavior] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayCapturedEvents=true, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                EventPoller=mockPoller, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyNotCalled( ...
                withAnyInputs(displayerBehavior.displayEvents), ...
                "displayEvents should not be called when poller is present" ...
            );
        end

        function testEvaluateWithCapture_WithEventPoller_UserError_StillStopsPoller(testCase)
            % Arrange
            events = struct('type', {'stdout'}, 'payload', {'partial'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockPoller, pollerBehavior] = testCase.createMockEventPoller(events);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            try
                mcpserver.internal.evaluateWithCapture( ...
                    "error('test:e', 'boom')", ...
                    ShowFigureWindows=false, ...
                    DisplayDuringExecution=false, ...
                    FigureVisibilityController=mockController, ...
                    EventPoller=mockPoller, ...
                    EventDisplayer=mockDisplayer ...
                );
            catch
            end

            % Assert
            testCase.verifyCalled( ...
                pollerBehavior.stop().withExactInputs(), ...
                "stop() should be called even when user code errors" ...
            );
            testCase.verifyCalled( ...
                pollerBehavior.flush().withExactInputs(), ...
                "flush() should be called even when user code errors" ...
            );
        end

        function testEvaluateWithCapture_DisplayDuringExecutionTrue_CreatesPollerAutomatically(testCase)
            % Arrange
            [mockController, ~] = testCase.createMockVisibilityController(false);

            % Act & Assert
            testCase.verifyWarningFree( ...
                @() mcpserver.internal.evaluateWithCapture( ...
                    "x = 1;", ...
                    ShowFigureWindows=false, ...
                    DisplayDuringExecution=true, ...
                    FigureVisibilityController=mockController ...
                ), ...
                "evaluateWithCapture should work with auto-created poller");
        end

        function testEvaluateWithCapture_DisplayDuringExecutionFalse_NoPollerCreated(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockEventSource, eventBehavior] = testCase.createMockEventSource(expectedEvents);
            [mockDisplayer, displayerBehavior] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayCapturedEvents=true, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                CapturedEventProvider=mockEventSource, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyCalled( ...
                eventBehavior.getEvents().withExactInputs(), ...
                "CapturedEventProvider.getEvents() should be used as event source" ...
            );
            testCase.verifyCalled( ...
                displayerBehavior.displayEvents(expectedEvents), ...
                "Post-hoc displayEvents should be called when no poller" ...
            );
        end

        function testEvaluateWithCapture_DisplayDuringExecutionTrue_ExplicitPollerTakesPrecedence(testCase)
            % Arrange
            events = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockPoller, pollerBehavior] = testCase.createMockEventPoller(events);
            [mockDisplayer, ~] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayDuringExecution=true, ...
                FigureVisibilityController=mockController, ...
                EventPoller=mockPoller, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyCalled( ...
                pollerBehavior.start().withExactInputs(), ...
                "Explicit poller should be used when provided" ...
            );
        end

        function testEvaluateWithCapture_DisplayDuringExecutionFalse_DisplayCapturedEventsTrue_NoDoubleDisplay(testCase)
            % Arrange
            events = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockPoller, ~] = testCase.createMockEventPoller(events);
            [mockDisplayer, displayerBehavior] = testCase.createMockEventDisplayer();

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayCapturedEvents=true, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                EventPoller=mockPoller, ...
                EventDisplayer=mockDisplayer ...
            );

            % Assert
            testCase.verifyNotCalled( ...
                withAnyInputs(displayerBehavior.displayEvents), ...
                "Post-hoc display should be skipped when poller is active to avoid double display" ...
            );
        end

        function testEvaluateWithCapture_DisplayDuringExecutionFalse_DisplayCapturedEventsFalse_FullySilent(testCase)
            % Arrange
            expectedEvents = struct('type', {'stdout'}, 'payload', {'hello'});
            [mockController, ~] = testCase.createMockVisibilityController(false);
            [mockEventSource, ~] = testCase.createMockEventSource(expectedEvents);
            [mockDisplayer, displayerBehavior] = testCase.createMockEventDisplayer();
            builder = testCase.createPassthroughOutputBuilder();

            % Act
            results = mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                ShowFigureWindows=false, ...
                DisplayCapturedEvents=false, ...
                DisplayDuringExecution=false, ...
                FigureVisibilityController=mockController, ...
                CapturedEventProvider=mockEventSource, ...
                EventDisplayer=mockDisplayer, ...
                OutputBuilder=builder ...
            );

            % Assert
            testCase.verifyNotCalled( ...
                withAnyInputs(displayerBehavior.displayEvents), ...
                "No display should occur when both display options are false" ...
            );
            testCase.verifyEqual(results, {expectedEvents}, ...
                "Events should still be returned even in fully silent mode" ...
            );
        end

        function testEvaluateWithCapture_DefaultOptions_ShowFiguresTrue(testCase)
            % Arrange
            [mockController, behavior] = testCase.createMockVisibilityController(true);

            % Act
            mcpserver.internal.evaluateWithCapture( ...
                "x = 1;", ...
                FigureVisibilityController=mockController ...
            );

            % Assert
            testCase.verifyCalled( ...
                behavior.show().withExactInputs(), ...
                "ShowFigureWindows should default to true" ...
            );
        end
    end

end

function cleanupScratch(scratchDir)
    if any(strcmp(strsplit(path, pathsep), char(scratchDir)))
        rmpath(scratchDir);
    end
    if isfolder(scratchDir)
        rmdir(scratchDir, 's');
    end
end
