// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/server/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/wire/adaptor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplicationFactory creates a new instance of MockApplicationFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplicationFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplicationFactory {
	mock := &MockApplicationFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplicationFactory is an autogenerated mock type for the ApplicationFactory type
type MockApplicationFactory struct {
	mock.Mock
}

type MockApplicationFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplicationFactory) EXPECT() *MockApplicationFactory_Expecter {
	return &MockApplicationFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockApplicationFactory
func (_mock *MockApplicationFactory) New(definition1 definition.Definition) adaptor.Application {
	ret := _mock.Called(definition1)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 adaptor.Application
	if returnFunc, ok := ret.Get(0).(func(definition.Definition) adaptor.Application); ok {
		r0 = returnFunc(definition1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adaptor.Application)
		}
	}
	return r0
}

// MockApplicationFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockApplicationFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - definition1 definition.Definition
func (_e *MockApplicationFactory_Expecter) New(definition1 interface{}) *MockApplicationFactory_New_Call {
	return &MockApplicationFactory_New_Call{Call: _e.mock.On("New", definition1)}
}

func (_c *MockApplicationFactory_New_Call) Run(run func(definition1 definition.Definition)) *MockApplicationFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 definition.Definition
		if args[0] != nil {
			arg0 = args[0].(definition.Definition)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockApplicationFactory_New_Call) Return(application adaptor.Application) *MockApplicationFactory_New_Call {
	_c.Call.Return(application)
	return _c
}

func (_c *MockApplicationFactory_New_Call) RunAndReturn(run func(definition1 definition.Definition) adaptor.Application) *MockApplicationFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
