// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/wire/adaptor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplication creates a new instance of MockApplication. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplication {
	mock := &MockApplication{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplication is an autogenerated mock type for the Application type
type MockApplication struct {
	mock.Mock
}

type MockApplication_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplication) EXPECT() *MockApplication_Expecter {
	return &MockApplication_Expecter{mock: &_m.Mock}
}

// MessageCatalog provides a mock function for the type MockApplication
func (_mock *MockApplication) MessageCatalog() adaptor.MessageCatalog {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageCatalog")
	}

	var r0 adaptor.MessageCatalog
	if returnFunc, ok := ret.Get(0).(func() adaptor.MessageCatalog); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adaptor.MessageCatalog)
		}
	}
	return r0
}

// MockApplication_MessageCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageCatalog'
type MockApplication_MessageCatalog_Call struct {
	*mock.Call
}

// MessageCatalog is a helper method to define mock.On call
func (_e *MockApplication_Expecter) MessageCatalog() *MockApplication_MessageCatalog_Call {
	return &MockApplication_MessageCatalog_Call{Call: _e.mock.On("MessageCatalog")}
}

func (_c *MockApplication_MessageCatalog_Call) Run(run func()) *MockApplication_MessageCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplication_MessageCatalog_Call) Return(messageCatalog adaptor.MessageCatalog) *MockApplication_MessageCatalog_Call {
	_c.Call.Return(messageCatalog)
	return _c
}

func (_c *MockApplication_MessageCatalog_Call) RunAndReturn(run func() adaptor.MessageCatalog) *MockApplication_MessageCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// ModeSelector provides a mock function for the type MockApplication
func (_mock *MockApplication) ModeSelector() adaptor.ModeSelector {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModeSelector")
	}

	var r0 adaptor.ModeSelector
	if returnFunc, ok := ret.Get(0).(func() adaptor.ModeSelector); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adaptor.ModeSelector)
		}
	}
	return r0
}

// MockApplication_ModeSelector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModeSelector'
type MockApplication_ModeSelector_Call struct {
	*mock.Call
}

// ModeSelector is a helper method to define mock.On call
func (_e *MockApplication_Expecter) ModeSelector() *MockApplication_ModeSelector_Call {
	return &MockApplication_ModeSelector_Call{Call: _e.mock.On("ModeSelector")}
}

func (_c *MockApplication_ModeSelector_Call) Run(run func()) *MockApplication_ModeSelector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplication_ModeSelector_Call) Return(modeSelector adaptor.ModeSelector) *MockApplication_ModeSelector_Call {
	_c.Call.Return(modeSelector)
	return _c
}

func (_c *MockApplication_ModeSelector_Call) RunAndReturn(run func() adaptor.ModeSelector) *MockApplication_ModeSelector_Call {
	_c.Call.Return(run)
	return _c
}
