// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// LogLevel provides a mock function for the type MockConfig
func (_mock *MockConfig) LogLevel() entities.LogLevel {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogLevel")
	}

	var r0 entities.LogLevel
	if returnFunc, ok := ret.Get(0).(func() entities.LogLevel); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(entities.LogLevel)
	}
	return r0
}

// MockConfig_LogLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogLevel'
type MockConfig_LogLevel_Call struct {
	*mock.Call
}

// LogLevel is a helper method to define mock.On call
func (_e *MockConfig_Expecter) LogLevel() *MockConfig_LogLevel_Call {
	return &MockConfig_LogLevel_Call{Call: _e.mock.On("LogLevel")}
}

func (_c *MockConfig_LogLevel_Call) Run(run func()) *MockConfig_LogLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfig_LogLevel_Call) Return(logLevel entities.LogLevel) *MockConfig_LogLevel_Call {
	_c.Call.Return(logLevel)
	return _c
}

func (_c *MockConfig_LogLevel_Call) RunAndReturn(run func() entities.LogLevel) *MockConfig_LogLevel_Call {
	_c.Call.Return(run)
	return _c
}
