// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

type Error interface {
	marker()
	Error() string
}

// StartupErrors_BadFlag_Error defines an error corresponding to the "StartupErrors_BadFlag" message catalog message
type StartupErrors_BadFlag_Error struct {
	Attr0 string
	Attr1 string
	Attr2 string
}

// Error makes StartupErrors_BadFlag_Error satisfy the error interface.
func (e *StartupErrors_BadFlag_Error) Error() string {
	return "StartupErrors_BadFlag_Error"
}

func (*StartupErrors_BadFlag_Error) marker() {}

// New_StartupErrors_BadFlag_Error makes a new StartupErrors_BadFlag_Error error.
func New_StartupErrors_BadFlag_Error(
	attr0 string,
	attr1 string,
	attr2 string,
) *StartupErrors_BadFlag_Error {
	return &StartupErrors_BadFlag_Error{
		Attr0: attr0,
		Attr1: attr1,
		Attr2: attr2,
	}
}

// StartupErrors_BadSyntax_Error defines an error corresponding to the "StartupErrors_BadSyntax" message catalog message
type StartupErrors_BadSyntax_Error struct {
	Attr0 string
	Attr1 string
	Attr2 string
}

// Error makes StartupErrors_BadSyntax_Error satisfy the error interface.
func (e *StartupErrors_BadSyntax_Error) Error() string {
	return "StartupErrors_BadSyntax_Error"
}

func (*StartupErrors_BadSyntax_Error) marker() {}

// New_StartupErrors_BadSyntax_Error makes a new StartupErrors_BadSyntax_Error error.
func New_StartupErrors_BadSyntax_Error(
	attr0 string,
	attr1 string,
	attr2 string,
) *StartupErrors_BadSyntax_Error {
	return &StartupErrors_BadSyntax_Error{
		Attr0: attr0,
		Attr1: attr1,
		Attr2: attr2,
	}
}

// StartupErrors_BadValue_Error defines an error corresponding to the "StartupErrors_BadValue" message catalog message
type StartupErrors_BadValue_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_BadValue_Error satisfy the error interface.
func (e *StartupErrors_BadValue_Error) Error() string {
	return "StartupErrors_BadValue_Error"
}

func (*StartupErrors_BadValue_Error) marker() {}

// New_StartupErrors_BadValue_Error makes a new StartupErrors_BadValue_Error error.
func New_StartupErrors_BadValue_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_BadValue_Error {
	return &StartupErrors_BadValue_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}

// StartupErrors_FailedToCreateLogFile_Error defines an error corresponding to the "StartupErrors_FailedToCreateLogFile" message catalog message
type StartupErrors_FailedToCreateLogFile_Error struct {
	Attr0 string
}

// Error makes StartupErrors_FailedToCreateLogFile_Error satisfy the error interface.
func (e *StartupErrors_FailedToCreateLogFile_Error) Error() string {
	return "StartupErrors_FailedToCreateLogFile_Error"
}

func (*StartupErrors_FailedToCreateLogFile_Error) marker() {}

// New_StartupErrors_FailedToCreateLogFile_Error makes a new StartupErrors_FailedToCreateLogFile_Error error.
func New_StartupErrors_FailedToCreateLogFile_Error(
	attr0 string,
) *StartupErrors_FailedToCreateLogFile_Error {
	return &StartupErrors_FailedToCreateLogFile_Error{
		Attr0: attr0,
	}
}

// StartupErrors_InvalidLogLevel_Error defines an error corresponding to the "StartupErrors_InvalidLogLevel" message catalog message
type StartupErrors_InvalidLogLevel_Error struct {
	Attr0 string
}

// Error makes StartupErrors_InvalidLogLevel_Error satisfy the error interface.
func (e *StartupErrors_InvalidLogLevel_Error) Error() string {
	return "StartupErrors_InvalidLogLevel_Error"
}

func (*StartupErrors_InvalidLogLevel_Error) marker() {}

// New_StartupErrors_InvalidLogLevel_Error makes a new StartupErrors_InvalidLogLevel_Error error.
func New_StartupErrors_InvalidLogLevel_Error(
	attr0 string,
) *StartupErrors_InvalidLogLevel_Error {
	return &StartupErrors_InvalidLogLevel_Error{
		Attr0: attr0,
	}
}

// StartupErrors_MissingValue_Error defines an error corresponding to the "StartupErrors_MissingValue" message catalog message
type StartupErrors_MissingValue_Error struct {
	Attr0 string
}

// Error makes StartupErrors_MissingValue_Error satisfy the error interface.
func (e *StartupErrors_MissingValue_Error) Error() string {
	return "StartupErrors_MissingValue_Error"
}

func (*StartupErrors_MissingValue_Error) marker() {}

// New_StartupErrors_MissingValue_Error makes a new StartupErrors_MissingValue_Error error.
func New_StartupErrors_MissingValue_Error(
	attr0 string,
) *StartupErrors_MissingValue_Error {
	return &StartupErrors_MissingValue_Error{
		Attr0: attr0,
	}
}

// StartupErrors_ParseFailed_Error defines an error corresponding to the "StartupErrors_ParseFailed" message catalog message
type StartupErrors_ParseFailed_Error struct {
	Attr0 string
	Attr1 string
}

// Error makes StartupErrors_ParseFailed_Error satisfy the error interface.
func (e *StartupErrors_ParseFailed_Error) Error() string {
	return "StartupErrors_ParseFailed_Error"
}

func (*StartupErrors_ParseFailed_Error) marker() {}

// New_StartupErrors_ParseFailed_Error makes a new StartupErrors_ParseFailed_Error error.
func New_StartupErrors_ParseFailed_Error(
	attr0 string,
	attr1 string,
) *StartupErrors_ParseFailed_Error {
	return &StartupErrors_ParseFailed_Error{
		Attr0: attr0,
		Attr1: attr1,
	}
}
