// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

type localeKey string

const (
	Locale_en_US localeKey = "en_US"
)

// LocaleKey is a specific type to signify message catalog locales.
type LocaleKey interface {
	unseal() localeKey
}

func (l localeKey) unseal() localeKey { return l }

func LocaleFromString(locale string) (localeKey, bool) {
	key, ok := keyMap[locale]
	return key, ok
}

var keyMap = map[string]localeKey{
	string(Locale_en_US): Locale_en_US,
}
