// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

import "fmt"

// New_AddonManagerErrors_InstallFailed_Message_FromCatalog makes a new populated message string from key AddonManagerErrors_InstallFailed_Message using the provided catalog.
func New_AddonManagerErrors_InstallFailed_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(AddonManagerErrors_InstallFailed)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_AddonManagerErrors_InstallFailed_Message makes a new populated message string from key AddonManagerErrors_InstallFailed_Message using the provided catalog.
func New_AddonManagerErrors_InstallFailed_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_AddonManagerErrors_InstallFailed_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_CLIMessages_BaseDirDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_BaseDirDescription_Message using the provided catalog.
func New_CLIMessages_BaseDirDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_BaseDirDescription)
	return text
}

// New_CLIMessages_BaseDirDescription_Message makes a new populated message string from key CLIMessages_BaseDirDescription_Message using the provided catalog.
func New_CLIMessages_BaseDirDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_BaseDirDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_DisableTelemetryDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_DisableTelemetryDescription_Message using the provided catalog.
func New_CLIMessages_DisableTelemetryDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_DisableTelemetryDescription)
	return text
}

// New_CLIMessages_DisableTelemetryDescription_Message makes a new populated message string from key CLIMessages_DisableTelemetryDescription_Message using the provided catalog.
func New_CLIMessages_DisableTelemetryDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_DisableTelemetryDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_DisplayModeDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_DisplayModeDescription_Message using the provided catalog.
func New_CLIMessages_DisplayModeDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_DisplayModeDescription)
	return text
}

// New_CLIMessages_DisplayModeDescription_Message makes a new populated message string from key CLIMessages_DisplayModeDescription_Message using the provided catalog.
func New_CLIMessages_DisplayModeDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_DisplayModeDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_ExtensionFileDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_ExtensionFileDescription_Message using the provided catalog.
func New_CLIMessages_ExtensionFileDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_ExtensionFileDescription)
	return text
}

// New_CLIMessages_ExtensionFileDescription_Message makes a new populated message string from key CLIMessages_ExtensionFileDescription_Message using the provided catalog.
func New_CLIMessages_ExtensionFileDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_ExtensionFileDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_GreetingOnConnect_Message_FromCatalog makes a new populated message string from key CLIMessages_GreetingOnConnect_Message using the provided catalog.
func New_CLIMessages_GreetingOnConnect_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(CLIMessages_GreetingOnConnect)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_CLIMessages_GreetingOnConnect_Message makes a new populated message string from key CLIMessages_GreetingOnConnect_Message using the provided catalog.
func New_CLIMessages_GreetingOnConnect_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_GreetingOnConnect_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_CLIMessages_HelpDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_HelpDescription_Message using the provided catalog.
func New_CLIMessages_HelpDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_HelpDescription)
	return text
}

// New_CLIMessages_HelpDescription_Message makes a new populated message string from key CLIMessages_HelpDescription_Message using the provided catalog.
func New_CLIMessages_HelpDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_HelpDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_InitializeMATLABOnStartupDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_InitializeMATLABOnStartupDescription_Message using the provided catalog.
func New_CLIMessages_InitializeMATLABOnStartupDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_InitializeMATLABOnStartupDescription)
	return text
}

// New_CLIMessages_InitializeMATLABOnStartupDescription_Message makes a new populated message string from key CLIMessages_InitializeMATLABOnStartupDescription_Message using the provided catalog.
func New_CLIMessages_InitializeMATLABOnStartupDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_InitializeMATLABOnStartupDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_InternalUseDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_InternalUseDescription_Message using the provided catalog.
func New_CLIMessages_InternalUseDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_InternalUseDescription)
	return text
}

// New_CLIMessages_InternalUseDescription_Message makes a new populated message string from key CLIMessages_InternalUseDescription_Message using the provided catalog.
func New_CLIMessages_InternalUseDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_InternalUseDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_LogLevelDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_LogLevelDescription_Message using the provided catalog.
func New_CLIMessages_LogLevelDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_LogLevelDescription)
	return text
}

// New_CLIMessages_LogLevelDescription_Message makes a new populated message string from key CLIMessages_LogLevelDescription_Message using the provided catalog.
func New_CLIMessages_LogLevelDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_LogLevelDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_MATLABSessionModeDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_MATLABSessionModeDescription_Message using the provided catalog.
func New_CLIMessages_MATLABSessionModeDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_MATLABSessionModeDescription)
	return text
}

// New_CLIMessages_MATLABSessionModeDescription_Message makes a new populated message string from key CLIMessages_MATLABSessionModeDescription_Message using the provided catalog.
func New_CLIMessages_MATLABSessionModeDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_MATLABSessionModeDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_PreferredLocalMATLABRootDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_PreferredLocalMATLABRootDescription_Message using the provided catalog.
func New_CLIMessages_PreferredLocalMATLABRootDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_PreferredLocalMATLABRootDescription)
	return text
}

// New_CLIMessages_PreferredLocalMATLABRootDescription_Message makes a new populated message string from key CLIMessages_PreferredLocalMATLABRootDescription_Message using the provided catalog.
func New_CLIMessages_PreferredLocalMATLABRootDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_PreferredLocalMATLABRootDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_PreferredMATLABStartingDirectoryDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_PreferredMATLABStartingDirectoryDescription_Message using the provided catalog.
func New_CLIMessages_PreferredMATLABStartingDirectoryDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_PreferredMATLABStartingDirectoryDescription)
	return text
}

// New_CLIMessages_PreferredMATLABStartingDirectoryDescription_Message makes a new populated message string from key CLIMessages_PreferredMATLABStartingDirectoryDescription_Message using the provided catalog.
func New_CLIMessages_PreferredMATLABStartingDirectoryDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_PreferredMATLABStartingDirectoryDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_SetupMATLABDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_SetupMATLABDescription_Message using the provided catalog.
func New_CLIMessages_SetupMATLABDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_SetupMATLABDescription)
	return text
}

// New_CLIMessages_SetupMATLABDescription_Message makes a new populated message string from key CLIMessages_SetupMATLABDescription_Message using the provided catalog.
func New_CLIMessages_SetupMATLABDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_SetupMATLABDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_SuccessfullySetupMATLAB_Message_FromCatalog makes a new populated message string from key CLIMessages_SuccessfullySetupMATLAB_Message using the provided catalog.
func New_CLIMessages_SuccessfullySetupMATLAB_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_SuccessfullySetupMATLAB)
	return text
}

// New_CLIMessages_SuccessfullySetupMATLAB_Message makes a new populated message string from key CLIMessages_SuccessfullySetupMATLAB_Message using the provided catalog.
func New_CLIMessages_SuccessfullySetupMATLAB_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_SuccessfullySetupMATLAB_Message_FromCatalog(catalog)
}

// New_CLIMessages_TitleOnConnect_Message_FromCatalog makes a new populated message string from key CLIMessages_TitleOnConnect_Message using the provided catalog.
func New_CLIMessages_TitleOnConnect_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_TitleOnConnect)
	return text
}

// New_CLIMessages_TitleOnConnect_Message makes a new populated message string from key CLIMessages_TitleOnConnect_Message using the provided catalog.
func New_CLIMessages_TitleOnConnect_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_TitleOnConnect_Message_FromCatalog(catalog)
}

// New_CLIMessages_UseSingleMATLABSessionDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_UseSingleMATLABSessionDescription_Message using the provided catalog.
func New_CLIMessages_UseSingleMATLABSessionDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_UseSingleMATLABSessionDescription)
	return text
}

// New_CLIMessages_UseSingleMATLABSessionDescription_Message makes a new populated message string from key CLIMessages_UseSingleMATLABSessionDescription_Message using the provided catalog.
func New_CLIMessages_UseSingleMATLABSessionDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_UseSingleMATLABSessionDescription_Message_FromCatalog(catalog)
}

// New_CLIMessages_VersionDescription_Message_FromCatalog makes a new populated message string from key CLIMessages_VersionDescription_Message using the provided catalog.
func New_CLIMessages_VersionDescription_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(CLIMessages_VersionDescription)
	return text
}

// New_CLIMessages_VersionDescription_Message makes a new populated message string from key CLIMessages_VersionDescription_Message using the provided catalog.
func New_CLIMessages_VersionDescription_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_CLIMessages_VersionDescription_Message_FromCatalog(catalog)
}

// New_StartupErrors_ArgumentNotAllowedInSessionMode_Message_FromCatalog makes a new populated message string from key StartupErrors_ArgumentNotAllowedInSessionMode_Message using the provided catalog.
func New_StartupErrors_ArgumentNotAllowedInSessionMode_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_ArgumentNotAllowedInSessionMode)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_ArgumentNotAllowedInSessionMode_Message makes a new populated message string from key StartupErrors_ArgumentNotAllowedInSessionMode_Message using the provided catalog.
func New_StartupErrors_ArgumentNotAllowedInSessionMode_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_ArgumentNotAllowedInSessionMode_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_BadFlag_Message_FromCatalog makes a new populated message string from key StartupErrors_BadFlag_Message using the provided catalog.
func New_StartupErrors_BadFlag_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
	attr2 string,
) string {
	text := catalog.Get(StartupErrors_BadFlag)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
		attr2,
	)
}

// New_StartupErrors_BadFlag_Message makes a new populated message string from key StartupErrors_BadFlag_Message using the provided catalog.
func New_StartupErrors_BadFlag_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
	attr2 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_BadFlag_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
		attr2,
	)
}

// New_StartupErrors_BadSyntax_Message_FromCatalog makes a new populated message string from key StartupErrors_BadSyntax_Message using the provided catalog.
func New_StartupErrors_BadSyntax_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
	attr2 string,
) string {
	text := catalog.Get(StartupErrors_BadSyntax)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
		attr2,
	)
}

// New_StartupErrors_BadSyntax_Message makes a new populated message string from key StartupErrors_BadSyntax_Message using the provided catalog.
func New_StartupErrors_BadSyntax_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
	attr2 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_BadSyntax_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
		attr2,
	)
}

// New_StartupErrors_BadValue_Message_FromCatalog makes a new populated message string from key StartupErrors_BadValue_Message using the provided catalog.
func New_StartupErrors_BadValue_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_BadValue)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_BadValue_Message makes a new populated message string from key StartupErrors_BadValue_Message using the provided catalog.
func New_StartupErrors_BadValue_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_BadValue_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_BadValueForEnvVar_Message_FromCatalog makes a new populated message string from key StartupErrors_BadValueForEnvVar_Message using the provided catalog.
func New_StartupErrors_BadValueForEnvVar_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_BadValueForEnvVar)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_BadValueForEnvVar_Message makes a new populated message string from key StartupErrors_BadValueForEnvVar_Message using the provided catalog.
func New_StartupErrors_BadValueForEnvVar_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_BadValueForEnvVar_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_CustomToolNameCollisionAcrossFiles_Message_FromCatalog makes a new populated message string from key StartupErrors_CustomToolNameCollisionAcrossFiles_Message using the provided catalog.
func New_StartupErrors_CustomToolNameCollisionAcrossFiles_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
	attr2 string,
) string {
	text := catalog.Get(StartupErrors_CustomToolNameCollisionAcrossFiles)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
		attr2,
	)
}

// New_StartupErrors_CustomToolNameCollisionAcrossFiles_Message makes a new populated message string from key StartupErrors_CustomToolNameCollisionAcrossFiles_Message using the provided catalog.
func New_StartupErrors_CustomToolNameCollisionAcrossFiles_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
	attr2 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_CustomToolNameCollisionAcrossFiles_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
		attr2,
	)
}

// New_StartupErrors_CustomToolNameConflict_Message_FromCatalog makes a new populated message string from key StartupErrors_CustomToolNameConflict_Message using the provided catalog.
func New_StartupErrors_CustomToolNameConflict_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_CustomToolNameConflict)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_CustomToolNameConflict_Message makes a new populated message string from key StartupErrors_CustomToolNameConflict_Message using the provided catalog.
func New_StartupErrors_CustomToolNameConflict_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_CustomToolNameConflict_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_DuplicateParameter_Message_FromCatalog makes a new populated message string from key StartupErrors_DuplicateParameter_Message using the provided catalog.
func New_StartupErrors_DuplicateParameter_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
	attr2 string,
) string {
	text := catalog.Get(StartupErrors_DuplicateParameter)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
		attr2,
	)
}

// New_StartupErrors_DuplicateParameter_Message makes a new populated message string from key StartupErrors_DuplicateParameter_Message using the provided catalog.
func New_StartupErrors_DuplicateParameter_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
	attr2 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_DuplicateParameter_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
		attr2,
	)
}

// New_StartupErrors_DuplicateToolName_Message_FromCatalog makes a new populated message string from key StartupErrors_DuplicateToolName_Message using the provided catalog.
func New_StartupErrors_DuplicateToolName_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_DuplicateToolName)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_DuplicateToolName_Message makes a new populated message string from key StartupErrors_DuplicateToolName_Message using the provided catalog.
func New_StartupErrors_DuplicateToolName_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_DuplicateToolName_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_FailedToCreateDirectory_Message_FromCatalog makes a new populated message string from key StartupErrors_FailedToCreateDirectory_Message using the provided catalog.
func New_StartupErrors_FailedToCreateDirectory_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_FailedToCreateDirectory)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_FailedToCreateDirectory_Message makes a new populated message string from key StartupErrors_FailedToCreateDirectory_Message using the provided catalog.
func New_StartupErrors_FailedToCreateDirectory_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_FailedToCreateDirectory_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_FailedToCreateFile_Message_FromCatalog makes a new populated message string from key StartupErrors_FailedToCreateFile_Message using the provided catalog.
func New_StartupErrors_FailedToCreateFile_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_FailedToCreateFile)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_FailedToCreateFile_Message makes a new populated message string from key StartupErrors_FailedToCreateFile_Message using the provided catalog.
func New_StartupErrors_FailedToCreateFile_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_FailedToCreateFile_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_FailedToCreateLogFile_Message_FromCatalog makes a new populated message string from key StartupErrors_FailedToCreateLogFile_Message using the provided catalog.
func New_StartupErrors_FailedToCreateLogFile_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_FailedToCreateLogFile)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_FailedToCreateLogFile_Message makes a new populated message string from key StartupErrors_FailedToCreateLogFile_Message using the provided catalog.
func New_StartupErrors_FailedToCreateLogFile_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_FailedToCreateLogFile_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_FailedToCreateSubdirectory_Message_FromCatalog makes a new populated message string from key StartupErrors_FailedToCreateSubdirectory_Message using the provided catalog.
func New_StartupErrors_FailedToCreateSubdirectory_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_FailedToCreateSubdirectory)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_FailedToCreateSubdirectory_Message makes a new populated message string from key StartupErrors_FailedToCreateSubdirectory_Message using the provided catalog.
func New_StartupErrors_FailedToCreateSubdirectory_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_FailedToCreateSubdirectory_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_FailedToGetExecutablePath_Message_FromCatalog makes a new populated message string from key StartupErrors_FailedToGetExecutablePath_Message using the provided catalog.
func New_StartupErrors_FailedToGetExecutablePath_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(StartupErrors_FailedToGetExecutablePath)
	return text
}

// New_StartupErrors_FailedToGetExecutablePath_Message makes a new populated message string from key StartupErrors_FailedToGetExecutablePath_Message using the provided catalog.
func New_StartupErrors_FailedToGetExecutablePath_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_FailedToGetExecutablePath_Message_FromCatalog(catalog)
}

// New_StartupErrors_FailedToParseExtensionFile_Message_FromCatalog makes a new populated message string from key StartupErrors_FailedToParseExtensionFile_Message using the provided catalog.
func New_StartupErrors_FailedToParseExtensionFile_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_FailedToParseExtensionFile)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_FailedToParseExtensionFile_Message makes a new populated message string from key StartupErrors_FailedToParseExtensionFile_Message using the provided catalog.
func New_StartupErrors_FailedToParseExtensionFile_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_FailedToParseExtensionFile_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_FailedToReadExtensionFile_Message_FromCatalog makes a new populated message string from key StartupErrors_FailedToReadExtensionFile_Message using the provided catalog.
func New_StartupErrors_FailedToReadExtensionFile_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_FailedToReadExtensionFile)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_FailedToReadExtensionFile_Message makes a new populated message string from key StartupErrors_FailedToReadExtensionFile_Message using the provided catalog.
func New_StartupErrors_FailedToReadExtensionFile_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_FailedToReadExtensionFile_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_FailedToStartWatchdogProcess_Message_FromCatalog makes a new populated message string from key StartupErrors_FailedToStartWatchdogProcess_Message using the provided catalog.
func New_StartupErrors_FailedToStartWatchdogProcess_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(StartupErrors_FailedToStartWatchdogProcess)
	return text
}

// New_StartupErrors_FailedToStartWatchdogProcess_Message makes a new populated message string from key StartupErrors_FailedToStartWatchdogProcess_Message using the provided catalog.
func New_StartupErrors_FailedToStartWatchdogProcess_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_FailedToStartWatchdogProcess_Message_FromCatalog(catalog)
}

// New_StartupErrors_GenericInitializeFailure_Message_FromCatalog makes a new populated message string from key StartupErrors_GenericInitializeFailure_Message using the provided catalog.
func New_StartupErrors_GenericInitializeFailure_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(StartupErrors_GenericInitializeFailure)
	return text
}

// New_StartupErrors_GenericInitializeFailure_Message makes a new populated message string from key StartupErrors_GenericInitializeFailure_Message using the provided catalog.
func New_StartupErrors_GenericInitializeFailure_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_GenericInitializeFailure_Message_FromCatalog(catalog)
}

// New_StartupErrors_InvalidDisplayMode_Message_FromCatalog makes a new populated message string from key StartupErrors_InvalidDisplayMode_Message using the provided catalog.
func New_StartupErrors_InvalidDisplayMode_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_InvalidDisplayMode)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_InvalidDisplayMode_Message makes a new populated message string from key StartupErrors_InvalidDisplayMode_Message using the provided catalog.
func New_StartupErrors_InvalidDisplayMode_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_InvalidDisplayMode_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_InvalidLogLevel_Message_FromCatalog makes a new populated message string from key StartupErrors_InvalidLogLevel_Message using the provided catalog.
func New_StartupErrors_InvalidLogLevel_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_InvalidLogLevel)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_InvalidLogLevel_Message makes a new populated message string from key StartupErrors_InvalidLogLevel_Message using the provided catalog.
func New_StartupErrors_InvalidLogLevel_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_InvalidLogLevel_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_InvalidMATLABSessionMode_Message_FromCatalog makes a new populated message string from key StartupErrors_InvalidMATLABSessionMode_Message using the provided catalog.
func New_StartupErrors_InvalidMATLABSessionMode_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_InvalidMATLABSessionMode)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_InvalidMATLABSessionMode_Message makes a new populated message string from key StartupErrors_InvalidMATLABSessionMode_Message using the provided catalog.
func New_StartupErrors_InvalidMATLABSessionMode_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_InvalidMATLABSessionMode_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_InvalidParameterKey_Message_FromCatalog makes a new populated message string from key StartupErrors_InvalidParameterKey_Message using the provided catalog.
func New_StartupErrors_InvalidParameterKey_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_InvalidParameterKey)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_InvalidParameterKey_Message makes a new populated message string from key StartupErrors_InvalidParameterKey_Message using the provided catalog.
func New_StartupErrors_InvalidParameterKey_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_InvalidParameterKey_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_InvalidParameterType_Message_FromCatalog makes a new populated message string from key StartupErrors_InvalidParameterType_Message using the provided catalog.
func New_StartupErrors_InvalidParameterType_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_InvalidParameterType)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_InvalidParameterType_Message makes a new populated message string from key StartupErrors_InvalidParameterType_Message using the provided catalog.
func New_StartupErrors_InvalidParameterType_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_InvalidParameterType_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_InvalidToolDefinition_Message_FromCatalog makes a new populated message string from key StartupErrors_InvalidToolDefinition_Message using the provided catalog.
func New_StartupErrors_InvalidToolDefinition_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_InvalidToolDefinition)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_InvalidToolDefinition_Message makes a new populated message string from key StartupErrors_InvalidToolDefinition_Message using the provided catalog.
func New_StartupErrors_InvalidToolDefinition_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_InvalidToolDefinition_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_InvalidToolInputSchema_Message_FromCatalog makes a new populated message string from key StartupErrors_InvalidToolInputSchema_Message using the provided catalog.
func New_StartupErrors_InvalidToolInputSchema_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_InvalidToolInputSchema)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_InvalidToolInputSchema_Message makes a new populated message string from key StartupErrors_InvalidToolInputSchema_Message using the provided catalog.
func New_StartupErrors_InvalidToolInputSchema_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_InvalidToolInputSchema_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_InvalidToolSignature_Message_FromCatalog makes a new populated message string from key StartupErrors_InvalidToolSignature_Message using the provided catalog.
func New_StartupErrors_InvalidToolSignature_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_InvalidToolSignature)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_InvalidToolSignature_Message makes a new populated message string from key StartupErrors_InvalidToolSignature_Message using the provided catalog.
func New_StartupErrors_InvalidToolSignature_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_InvalidToolSignature_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_MissingToolSignature_Message_FromCatalog makes a new populated message string from key StartupErrors_MissingToolSignature_Message using the provided catalog.
func New_StartupErrors_MissingToolSignature_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_MissingToolSignature)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_MissingToolSignature_Message makes a new populated message string from key StartupErrors_MissingToolSignature_Message using the provided catalog.
func New_StartupErrors_MissingToolSignature_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_MissingToolSignature_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_MissingValue_Message_FromCatalog makes a new populated message string from key StartupErrors_MissingValue_Message using the provided catalog.
func New_StartupErrors_MissingValue_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
) string {
	text := catalog.Get(StartupErrors_MissingValue)
	return fmt.Sprintf(
		text,
		attr0,
	)
}

// New_StartupErrors_MissingValue_Message makes a new populated message string from key StartupErrors_MissingValue_Message using the provided catalog.
func New_StartupErrors_MissingValue_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_MissingValue_Message_FromCatalog(
		catalog,
		attr0,
	)
}

// New_StartupErrors_ParseFailed_Message_FromCatalog makes a new populated message string from key StartupErrors_ParseFailed_Message using the provided catalog.
func New_StartupErrors_ParseFailed_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_ParseFailed)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_ParseFailed_Message makes a new populated message string from key StartupErrors_ParseFailed_Message using the provided catalog.
func New_StartupErrors_ParseFailed_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_ParseFailed_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}

// New_StartupErrors_TelemetryInitializationFailed_Message_FromCatalog makes a new populated message string from key StartupErrors_TelemetryInitializationFailed_Message using the provided catalog.
func New_StartupErrors_TelemetryInitializationFailed_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
) string {
	text := catalog.Get(StartupErrors_TelemetryInitializationFailed)
	return text
}

// New_StartupErrors_TelemetryInitializationFailed_Message makes a new populated message string from key StartupErrors_TelemetryInitializationFailed_Message using the provided catalog.
func New_StartupErrors_TelemetryInitializationFailed_Message_FromLocale(
	locale LocaleKey,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_TelemetryInitializationFailed_Message_FromCatalog(catalog)
}

// New_StartupErrors_WriteError_Message_FromCatalog makes a new populated message string from key StartupErrors_WriteError_Message using the provided catalog.
func New_StartupErrors_WriteError_Message_FromCatalog(
	catalog LocaleSpecificCatalog,
	attr0 string,
	attr1 string,
) string {
	text := catalog.Get(StartupErrors_WriteError)
	return fmt.Sprintf(
		text,
		attr0,
		attr1,
	)
}

// New_StartupErrors_WriteError_Message makes a new populated message string from key StartupErrors_WriteError_Message using the provided catalog.
func New_StartupErrors_WriteError_Message_FromLocale(
	locale LocaleKey,
	attr0 string,
	attr1 string,
) string {
	catalog := NewCatalog(locale)
	return New_StartupErrors_WriteError_Message_FromCatalog(
		catalog,
		attr0,
		attr1,
	)
}
