// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/checkmatlabcode"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCodeAnalyzer creates a new instance of MockCodeAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodeAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodeAnalyzer {
	mock := &MockCodeAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCodeAnalyzer is an autogenerated mock type for the CodeAnalyzer type
type MockCodeAnalyzer struct {
	mock.Mock
}

type MockCodeAnalyzer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodeAnalyzer) EXPECT() *MockCodeAnalyzer_Expecter {
	return &MockCodeAnalyzer_Expecter{mock: &_m.Mock}
}

// AnalyzeCode provides a mock function for the type MockCodeAnalyzer
func (_mock *MockCodeAnalyzer) AnalyzeCode(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient, scriptPath string) ([]checkmatlabcode.CodeIssue, error) {
	ret := _mock.Called(ctx, logger, client, scriptPath)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeCode")
	}

	var r0 []checkmatlabcode.CodeIssue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient, string) ([]checkmatlabcode.CodeIssue, error)); ok {
		return returnFunc(ctx, logger, client, scriptPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient, string) []checkmatlabcode.CodeIssue); ok {
		r0 = returnFunc(ctx, logger, client, scriptPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]checkmatlabcode.CodeIssue)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.MATLABSessionClient, string) error); ok {
		r1 = returnFunc(ctx, logger, client, scriptPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCodeAnalyzer_AnalyzeCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyzeCode'
type MockCodeAnalyzer_AnalyzeCode_Call struct {
	*mock.Call
}

// AnalyzeCode is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
//   - client entities.MATLABSessionClient
//   - scriptPath string
func (_e *MockCodeAnalyzer_Expecter) AnalyzeCode(ctx interface{}, logger interface{}, client interface{}, scriptPath interface{}) *MockCodeAnalyzer_AnalyzeCode_Call {
	return &MockCodeAnalyzer_AnalyzeCode_Call{Call: _e.mock.On("AnalyzeCode", ctx, logger, client, scriptPath)}
}

func (_c *MockCodeAnalyzer_AnalyzeCode_Call) Run(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient, scriptPath string)) *MockCodeAnalyzer_AnalyzeCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.MATLABSessionClient
		if args[2] != nil {
			arg2 = args[2].(entities.MATLABSessionClient)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCodeAnalyzer_AnalyzeCode_Call) Return(codeIssues []checkmatlabcode.CodeIssue, err error) *MockCodeAnalyzer_AnalyzeCode_Call {
	_c.Call.Return(codeIssues, err)
	return _c
}

func (_c *MockCodeAnalyzer_AnalyzeCode_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger, client entities.MATLABSessionClient, scriptPath string) ([]checkmatlabcode.CodeIssue, error)) *MockCodeAnalyzer_AnalyzeCode_Call {
	_c.Call.Return(run)
	return _c
}
