// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/adaptors/telemetry"
	"github.com/matlab/matlab-mcp-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTelemetryFactory creates a new instance of MockTelemetryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetryFactory {
	mock := &MockTelemetryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelemetryFactory is an autogenerated mock type for the TelemetryFactory type
type MockTelemetryFactory struct {
	mock.Mock
}

type MockTelemetryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetryFactory) EXPECT() *MockTelemetryFactory_Expecter {
	return &MockTelemetryFactory_Expecter{mock: &_m.Mock}
}

// Telemetry provides a mock function for the type MockTelemetryFactory
func (_mock *MockTelemetryFactory) Telemetry() (telemetry.Telemetry, messages.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Telemetry")
	}

	var r0 telemetry.Telemetry
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func() (telemetry.Telemetry, messages.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() telemetry.Telemetry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telemetry.Telemetry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() messages.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockTelemetryFactory_Telemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Telemetry'
type MockTelemetryFactory_Telemetry_Call struct {
	*mock.Call
}

// Telemetry is a helper method to define mock.On call
func (_e *MockTelemetryFactory_Expecter) Telemetry() *MockTelemetryFactory_Telemetry_Call {
	return &MockTelemetryFactory_Telemetry_Call{Call: _e.mock.On("Telemetry")}
}

func (_c *MockTelemetryFactory_Telemetry_Call) Run(run func()) *MockTelemetryFactory_Telemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelemetryFactory_Telemetry_Call) Return(telemetry1 telemetry.Telemetry, error messages.Error) *MockTelemetryFactory_Telemetry_Call {
	_c.Call.Return(telemetry1, error)
	return _c
}

func (_c *MockTelemetryFactory_Telemetry_Call) RunAndReturn(run func() (telemetry.Telemetry, messages.Error)) *MockTelemetryFactory_Telemetry_Call {
	_c.Call.Return(run)
	return _c
}
