// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/services/localmatlabsession/directory"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionDirectoryFactory creates a new instance of MockSessionDirectoryFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionDirectoryFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionDirectoryFactory {
	mock := &MockSessionDirectoryFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionDirectoryFactory is an autogenerated mock type for the SessionDirectoryFactory type
type MockSessionDirectoryFactory struct {
	mock.Mock
}

type MockSessionDirectoryFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionDirectoryFactory) EXPECT() *MockSessionDirectoryFactory_Expecter {
	return &MockSessionDirectoryFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockSessionDirectoryFactory
func (_mock *MockSessionDirectoryFactory) New(logger entities.Logger) (directory.Directory, error) {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 directory.Directory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) (directory.Directory, error)); ok {
		return returnFunc(logger)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) directory.Directory); ok {
		r0 = returnFunc(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(directory.Directory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(entities.Logger) error); ok {
		r1 = returnFunc(logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionDirectoryFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockSessionDirectoryFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockSessionDirectoryFactory_Expecter) New(logger interface{}) *MockSessionDirectoryFactory_New_Call {
	return &MockSessionDirectoryFactory_New_Call{Call: _e.mock.On("New", logger)}
}

func (_c *MockSessionDirectoryFactory_New_Call) Run(run func(logger entities.Logger)) *MockSessionDirectoryFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionDirectoryFactory_New_Call) Return(directory1 directory.Directory, err error) *MockSessionDirectoryFactory_New_Call {
	_c.Call.Return(directory1, err)
	return _c
}

func (_c *MockSessionDirectoryFactory_New_Call) RunAndReturn(run func(logger entities.Logger) (directory.Directory, error)) *MockSessionDirectoryFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
